In [ ]:
import pandas as pd
from db import MyDB

In [ ]:
# 로컬 데이터베이스 class 생성
db = MyDB()

In [ ]:
# DataBase에 있는 emp, dept 테이블을 이용해서 select문 작성  // pandas를 이용해서 데이터프레임 생성 
query_1 = """
    SELECT * FROM `emp`
"""
sql_result = db.sql_query(query_1)
sql_result

In [ ]:
emp_df = pd.DataFrame(sql_result)
emp_df

In [ ]:
# read_csv() 함수를 이용하여 csv 파일 로드 
emp_df2 = pd.read_csv("../csv/emp.csv")
emp_df2

In [ ]:
dept_df = pd.read_csv("../csv/dept.csv")
dept_df

In [ ]:
query_2 = """
    SELECT * FROM `dept`
"""
pd.DataFrame(
    db.sql_query(query_2)
)

In [ ]:
# emp_df에서 SAL 컬럼의 데이터가 1500 이상인 사원의 모든 정보를 확인 
# DataFrame를 이용해서 확인 

# 조건 -> SAL 컬럼의 데이터가 1500 이상 (인덱스의 조건식)   //   사원의 모든 정보( 컬럼의 조건 모든 컬럼 )
index_flag = emp_df['SAL'] >= 1500
index_flag

In [ ]:
# 데이터프레임이 필터 -> loc[인덱스의 조건식, 컬럼의 조건식], iloc[인덱스의 위치, 컬럼의 위치]
emp_df.loc[index_flag, ]

In [ ]:
# SAL이 1500이상인 사원 정보를 출력한다. SQL 쿼리문 이용
# SELECT { 컬럼의 선택 || 컬럼의 연산 } FROM table명 WHERE 인덱스의 조건식 
query_3 = """
    SELECT * FROM `emp` WHERE `SAL` >= 1500
"""
pd.DataFrame(
    db.sql_query(query_3)
)

In [ ]:
# pandas 버전 
# SAL이 1500이상 이고 JOB이 MANAGER인 사원의 사원번호와 이름을 출력 
# 인덱스의 조건 : SAL이 1500 이상 & JOB이 MANAGER인 
# 컬럼의 조건  : 사원 정보 중 사원 번호, 사원 이름
index_flag1 = emp_df['SAL'] >= 1500
index_flag2 = emp_df['JOB'] == 'MANAGER'
col_flag = ['EMPNO', 'ENAME']
emp_df.loc[
    index_flag1 & index_flag2, 
    col_flag
]

In [ ]:
# SQL버전
query_4 = """
    SELECT `EMPNO`, `ENAME` FROM `emp` 
    WHERE `SAL` >= 1500 AND `JOB` = 'MANAGER'
"""
pd.DataFrame(
    db.sql_query(query_4)
)

In [ ]:
# sql 버전 
# SAL 1500이상 2500이하인 사원의 모든 정보 확인 
query_4 = """
    SELECT * FROM `emp` WHERE 
    `SAL` >= 1500 AND `SAL` <= 2500
"""
pd.DataFrame(
    db.sql_query(query_4)
)

In [ ]:
query_5 = """
    SELECT * FROM `emp` 
    WHERE `SAL` BETWEEN 1500 AND 2500
"""
pd.DataFrame(
    db.sql_query(query_5)
)

In [ ]:
# pandas 버전
# 인덱스 조건  : SAL이 1500 이상 그리고 SAL이 2500이하
index_flag1 = emp_df['SAL'] >= 1500
index_flag2 = emp_df['SAL'] <= 2500
emp_df.loc[ index_flag1 & index_flag2,  ]

In [ ]:
# 포함되어있는가? 포함(in) , 존재여부(is)
emp_df.loc[
    emp_df['SAL'].isin( range(1500, 2501) ), 
]

In [ ]:
# 사잇값 : between()
emp_df.loc[
    emp_df['SAL'].between(1500, 2500), 
]

In [ ]:
# JOB이 MANAGER이거나 SALESMAN 인 경우 모든 사원 정보를 확인 
# sql 
query_6 = """
    SELECT * FROM `emp` 
    WHERE 
    `JOB` = 'MANAGER' OR `JOB` = 'SALESMAN'
"""
pd.DataFrame(
    db.sql_query(query_6)
)

In [ ]:
query_7 = """
    SELECT * FROM `emp`
    WHERE 
    `JOB` IN ('MANAGER', 'SALESMAN')
"""
pd.DataFrame(
    db.sql_query(query_7)
)

In [ ]:
def sql(query):
    result = pd.DataFrame(
        db.sql_query(query)
    )
    return result

In [ ]:
# pandas  버전 
# 조건식을 2개 사용
flag1 = emp_df['JOB'] == 'MANAGER'
flag2 = emp_df['JOB'] == 'SALESMAN'
emp_df.loc[
    flag1 | flag2, 
]

In [ ]:
# 포함 여부 -> isin()
flag1 = emp_df['JOB'].isin( ['MANAGER', 'SALESMAN'] )
emp_df.loc[flag1, ]

In [ ]:
# emp table에서 ENAME이 s로 시작하는 사원의 정보를 확인 
# % -> python 특수 기능 (경로에 \가 포함되어있으면 \\, /로 변경 (r-string) ) -> %%로 이용
query_8 = """
    SELECT * FROM `emp` 
    WHERE 
    `ENAME` LIKE "s%%"
"""

sql(query_8)

In [ ]:
# pandas 에서 ENAME이 S로 시작하는 사원의 정보를 출력하시오
# sql은 대소문자를 구분하지 않지만 python은 대소문자 구분

# 찾는 단어 s | S
word = 's'

flag_list = []

for name in emp_df['ENAME']:
    # print(name)
    # 문자의 시작이 word와 같은 경우라면? --> startswith() | 문자에서 처음부터 word 길이까지를 추출
    # print(name[ : len(word) ])
    # print( name[ : len(word)].lower() == word.lower() )
    # print(name.lower().startswith(word.lower()))
    flag_list.append(
        # 특정 문자로 시작하는 경우 
        # name.lower().startswith(word.lower)
        # 특정 문자로 끝나는 경우
        # name.lower().endswith(word.lower())
        # 특정 문자가 포함(in)되어 있는 경우 -> 특정 문자가 name에 포함되어있는가?
        word.lower() in name.lower()
    )
# flag_list

In [ ]:
emp_df.loc[
    flag_list, 
]

In [ ]:
word = 's'
# 특정 문자로 시작하는 조건식 생성
emp_df['ENAME'].str.lower().str.startswith(word.lower())

In [ ]:
# 특정문자로 끝나는 조건식 생성 
emp_df['ENAME'].str.lower().str.endswith(word.lower())

In [ ]:
# 특정문자가 포함되어 있는 조건식 생성 
flag = emp_df['ENAME'].str.lower().str.contains(word.lower())

emp_df.loc[flag, ]

In [ ]:
# emp, dept 테이블
# 테이블 간의 결합 -> 사원의 정보 테이블과 부서의 정보 테이블 -> 조건에 맞게 결합이 되는 형태 -> 조인 결합 
# 조인 결합 -> pandas 에서는 merge() 함수를 이용

- 유니언 결합 
    - 단순 결합 (행, 열)
    - pandas에서는 concat( [데이터프레임, 데이터프레임, ...] ) 함수를 이용
    - 단순 결합의 형태이기 때문에 데이터프레임의 개수의 제한 x
        - 매개변수 
            - axis 
                - 행으로 결합한 것인가, 열로 결합할 것인가
            - ignore_index 
                - 결합되는 축을 초기화 할것인가
    - SQL에서는 UNION 키워드를 이용해서 결합 
        - SELECT문 UNION SELECT문
- 조인 결합 
    - 특정한 조건에 맞춰서 열을 결합 
    - 데이터프레임과 데이터프레임간의 결합  -> 특정 컬럼의 데이터들이 같은 값들로 이우러져있는 경우 열을 추가하는 방식 
    - pandas, DataFrame에 내장된 merge() 함수를 이용
    - 조건에 맞춰서 결합이 되기 때문에 데이터프레임은 2개 결합 
        - 매개변수 
            - on
                - 조건식 -> 2개의 데이터프레임이 모두 가지고 있는 컬럼의 이름 
                - 각 데이터프레임의 컬럼이 이름이 다른 경우에는 left_on, right_on 매개변수를 이용
            - how
                - 조인 결합의 방식 (left, right, inner, outer)
    - SQL에서는 JOIN 키워드를 이용해서 결합 
        - SELECT * FROM `table1` INNER JOIN `table2` ON `table1`.`COL` = `table2`.`COL`

In [ ]:
# 조인 결합 SQL 
query_9 = """
    SELECT * FROM 
    `emp` LEFT JOIN `dept`
    ON `emp`.`DEPTNO` = `dept`.`DEPTNO`
"""
sql(query_9)

In [ ]:
pd.merge(emp_df, dept_df, on='DEPTNO', how='left')

In [ ]:
dept_df2 = dept_df.copy()

In [ ]:
dept_df2.rename(
    columns={
        'DEPTNO' : 'DEPTNUM'
    }, inplace=True
)

In [ ]:
# merge 함수에서 결합하는 2개의 데이터프레임이 컬럼의 이름이 다른 경우 
# emp 테이블에 DEPTNO와 dept 테이블에서는 DEPTNUM의 데이터가 같은 경우 
pd.merge(
    emp_df, dept_df2, left_on='DEPTNO', right_on='DEPTNUM'  , how='left'
)

In [ ]:
# 유니언 결합 sql -> tran_1, tran_2 테이블을 유니언 결합 
query_10 = """
    SELECT 
    `transaction_id` `거래고유번호`, 
    `price` `가격`, 
    `payment_date` `거래일자`, 
    `customer_id` `고객고유번호` 
    FROM `tran_1`
    UNION 
    SELECT * FROM `tran_2`
"""
sql(query_10)

In [ ]:
tran_1 = pd.read_csv("../csv/tran_1.csv")
tran_2 = pd.read_csv("../csv/tran_2.csv")
tran_d1 = pd.read_csv("../csv/tran_d_1.csv")
tran_d2 = pd.read_csv("../csv/tran_d_2.csv")

In [ ]:
pd.concat([tran_1, tran_2], axis=0, ignore_index=True).rename(
    columns = {
        'transaction_id' : '거래고유번호', 
        'price' : '가격', 
        'payment_date' : '거래일자', 
        'customer_id' : '고객고유번호'
    }
)

In [ ]:
# tran_1와 tran_d_1 테이블을 조인 결합 
query_11 = """
    SELECT 
    `td1`.`transaction_id`, 
    `price`, 
    `payment_date`, 
    `quantity`
    FROM 
    `tran_1` `t1`
    LEFT JOIN 
    `tran_d_1` `td1`
    ON
    `t1`.`transaction_id` = `td1`.`transaction_id`
"""
sql(query_11)

In [ ]:
# 정렬 방식 -> pandas : sort_values()
# ORDER BY 컬럼명 ASC(기본값 - 생략 가능) | DESC(내림차순)
query_12 = """
    SELECT * FROM 
    `emp` ORDER BY `ENAME` DESC
"""
sql(query_12)

In [ ]:
emp_df.sort_values('ENAME', ascending=False)

In [108]:
# 그룹화 -> pandas groupby() -> 그룹화 연산 
# GROUP BY 
query_13 = """
    SELECT
    `JOB`,
    AVG(`SAL`) `AVG_SAL` , 
    SUM(`SAL`) `SUM_SAL`, 
    COUNT(`SAL`) `COUNT`
    FROM
    `emp`
    GROUP BY 
    `JOB`  
"""
sql(query_13)

접속된 서버가 존재함

         JOB      AVG_SAL  SUM_SAL  COUNT
0      CLERK  1037.500000   4150.0      4
1   SALESMAN  1400.000000   5600.0      4
2    MANAGER  2758.333333   8275.0      3
3    ANALYST  3000.000000   6000.0      2
4  PRESIDENT  5000.000000   5000.0      1

In [ ]:
emp_df[ ['JOB', 'SAL'] ].groupby('JOB').agg(['mean', 'sum', 'count'])

In [ ]:
# 서브 쿼리 
# 부서의 지역이 NEW YORK, CHICAGO인 사원의 정보를 확인 
# 부서 테이블의 뉴욕, 시카고인 부서의 번호를 받아서 사원 정보 테이블에 필터 
query_14 = """
    SELECT 
    * FROM `emp` 
    WHERE `DEPTNO` IN (10, 30)
"""
sql(query_14)

In [ ]:
dept_df
query_15 = """
    SELECT `DEPTNO`
    FROM `dept` 
    WHERE
    `LOC` IN ('NEW YORK', 'CHICAGO') 
"""
sql(query_15)

In [ ]:
query_16 = """
    SELECT * FROM `emp`
    WHERE 
    `DEPTNO` IN 
    (
        SELECT `DEPTNO` FROM `dept`
        WHERE LOC IN ('NEW YORK', 'CHICAGO')
    )
"""
sql(query_16)

In [ ]:
# 부서 정보에서 LOC 컬럼이 뉴욕, 시카고인 부서의 번호를 추출 
flag =  dept_df.loc[
    dept_df['LOC'].isin( ['NEW YORK', 'CHICAGO'] )
    ,'DEPTNO'
]

In [ ]:
emp_df.loc[emp_df['DEPTNO'].isin(flag), ]

In [113]:
# WHERE(인덱스 조건 - 필터) , GROUP BY(그룹화), HAVING(인덱스 조건 - 필터), ORDER BY(정렬)
# 1. WHERE(그룹화를 하기 전에 데이터를 필터)
# 2. GROUP BY(그룹화)
# 3. HAVING(그룹화 된 데이터에서 필터)
# 4. ORDER BY(최종 결과를 이용하여 정렬을 변경)
# 직종에서 SALESMAN을 제외하고 직종별로 그룹화를 하여 SAL의 평균을 구한뒤 평균의 값이 2500 이상인 데이터에서 평균 SAL이 높은 순서대로 출력

query_17 = """
    SELECT 
    `JOB`, AVG(`SAL`) `MEAN`
    FROM `emp`
    WHERE `JOB` != 'ANALYST' 
    GROUP BY `JOB`
    HAVING `MEAN` >= 2500 
    ORDER BY `MEAN` DESC
"""

sql(query_17)

접속된 서버가 존재함

         JOB         MEAN
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333

In [116]:
df = emp_df.loc[
    emp_df['JOB'] != 'ANALYST'
]

In [118]:
group_df = df[ ['JOB', 'SAL'] ].groupby('JOB').mean()

In [121]:
group_df = group_df.loc[
    group_df['SAL'] >= 2500
]

In [123]:
group_df.sort_values('SAL', ascending=False).reset_index()

         JOB          SAL
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333