In [1]:
import os 
from glob import glob
import pandas as pd

In [2]:
# 특정 경로에서 파일의 목록을 가져오는 기능 
os.listdir("./review")

['1-1.여성의류(196).json',
 '1-1.여성의류(197).json',
 '1-1.여성의류(198).json',
 '1-1.여성의류(199).json',
 '1-1.여성의류(200).json',
 '1-1.여성의류(201).json',
 '1-1.여성의류(202).json',
 '1-1.여성의류(203).json',
 '1-1.여성의류(204).json',
 '1-1.여성의류(205).json',
 '1-1.여성의류(206).json',
 '1-1.여성의류(207).json',
 '1-1.여성의류(208).json',
 '1-1.여성의류(209).json']

In [3]:
# glob 라이브러리 사용
# 장점 : 파일의 경로와 파일 명이 동시에 출력 
#       특정 확장자만 목록을 불러올수 있다. 
json_list = glob("./review/*.json")

In [4]:
# json_list를 이용하여 여러 파일들을 하나의 데이터프레임으로 결합 

# 비어있는 데이터프레임을 생성 
total_df = pd.DataFrame()

for file_path in json_list:
    # print(file_path)
    # break
    df = pd.read_json(file_path)
    # df를 total_df에 단순 행 결합 
    total_df = pd.concat( [total_df, df], axis = 0 )
total_df.reset_index(drop = True, inplace=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1423 entries, 0 to 1422
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            1423 non-null   int64
 1   RawText          1423 non-null   object
 2   Source           1423 non-null   object
 3   Domain           1423 non-null   object
 4   MainCategory     1423 non-null   object
 5   ProductName      1423 non-null   object
 6   Syllable         1423 non-null   int64
 7   Word             1423 non-null   int64
 8   GeneralPolarity  1418 non-null   float64
 9   Aspects          1423 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 111.3+ KB

In [5]:
total_df.head(2)

,Index,RawText,Source,Domain,MainCategory,ProductName,Syllable,Word,GeneralPolarity,Aspects
0,1024338,안녕하세요 이웃님들 반갑습니다. 요즘 날씨가 많이 쌀쌀해졌죠? 요즘 계절에 입으면 ...,SNS,패션,여성의류,OO 경량 다운 자켓,513,121,1.0,"[{'Aspect': '디자인', 'SentimentText': '딱 기본 스타일인..."
1,1024477,드디어 겨울이 찾아왔네요. 이제부터 슬슬 겨울 패딩 장만하셔야지요? 패딩 소개해 드...,SNS,패션,여성의류,OO 아** 구스코트,464,105,1.0,"[{'Aspect': '사이즈', 'SentimentText': '저는 블랙90 사..."

In [6]:
aspect_df = pd.DataFrame(sum(total_df['Aspects'], []))

In [7]:
aspect_df.head()

,Aspect,SentimentText,SentimentWord,SentimentPolarity
0,디자인,딱 기본 스타일인데 또 입은 거 보면 깔끔하게 저렴해보이지 않는 디자인이라서,11,1
1,두께,이것만 입기엔 얇지만,3,-1
2,기능,초겨울까지는 운동 갈때 안에 얇은 기능성 반팔 입고 요것만 입어도 꽤 따뜻해요.,12,1
3,색상,색상도 디자인도 무난해서,3,0
4,디자인,디자인도 무난해서,2,0

In [8]:
# 결측치가 존재하는가?
aspect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10962 entries, 0 to 10961
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Aspect             10962 non-null  object
 1   SentimentText      10962 non-null  object
 2   SentimentWord      10962 non-null  object
 3   SentimentPolarity  10962 non-null  object
dtypes: object(4)
memory usage: 342.7+ KB

In [9]:
aspect_df = aspect_df.map(lambda x : x.strip())

In [10]:
(aspect_df == '').sum()

Aspect               0
SentimentText        0
SentimentWord        0
SentimentPolarity    0
dtype: int64

In [11]:
# 종속 변수들의 데이터의 빈도수를 확인 
aspect_df['Aspect'].value_counts()

Aspect
디자인     1676
기능      1212
소재      1151
활용성      917
색상       855
핏        753
가격       679
사이즈      642
착용감      633
길이       496
품질       468
두께       353
신축성      277
무게       271
촉감       252
제품구성     169
마감       142
냄새        16
Name: count, dtype: int64

In [12]:
aspect_df['SentimentPolarity'].value_counts()

SentimentPolarity
1     9664
-1    1005
0      293
Name: count, dtype: int64

In [13]:
# 독립 변수에서 중복된 데이터가 존재하면 제거 
aspect_df.drop_duplicates('SentimentText', inplace=True)

In [14]:
aspect_df['SentimentPolarity'].value_counts()

SentimentPolarity
1     9183
-1     994
0      290
Name: count, dtype: int64

In [15]:
# 인덱스 초기화
aspect_df.reset_index(drop=True, inplace=True)

In [16]:
# 독립 변수를 토큰화 -> 벡터화 
from konlpy.tag import Okt
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
# 토큰화 과정에서 특정 품사들만 사용
# 명사, 동사, 형용사, 부사

okt = Okt()
allow_pos = ['Noun', 'Verb', 'Adjective', 'Adverb']

def tokenize(text):
    result = []
    for word, pos in okt.pos(text):
        if (pos in allow_pos) & (len(word) >= 2):
            result.append(word)
    return result

tokenize(
    aspect_df.loc[0, 'SentimentText']
)

['기본', '스타일', '입은', '보면', '깔끔하게', '저렴해', '보이지', '않는', '디자인']

In [18]:
vec = TfidfVectorizer(
    tokenizer= tokenize, 
    ngram_range= (1, 2), 
    min_df= 3, 
    max_df = 0.8, 
    max_features= 3000
)

In [19]:
aspect_df.columns

Index(['Aspect', 'SentimentText', 'SentimentWord', 'SentimentPolarity'], dtype='object')

In [20]:
X = aspect_df['SentimentText'].values
y1 = aspect_df['Aspect'].values
y2 = aspect_df['SentimentPolarity'].values

In [21]:
X_vec = vec.fit_transform(X)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [22]:
X_vec.shape

(10467, 3000)

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le1 = LabelEncoder()
y1_le = le1.fit_transform(y1) 
le2 = LabelEncoder()
y2_le = le2.fit_transform(y2)

In [25]:
from sklearn.svm import LinearSVC

In [26]:
svc1 = LinearSVC(class_weight='balanced', random_state=42)
svc2 = LinearSVC(class_weight='balanced', random_state=42)

In [27]:
svc1.fit(X_vec, y1_le)
svc2.fit(X_vec, y2_le)

LinearSVC(class_weight='balanced', random_state=42)

In [28]:
X_vec[-500:]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2937 stored elements and shape (500, 3000)>

In [29]:
y1_le[-500:]

array([ 6, 16,  4,  7, 13,  9, 10,  5, 16,  6, 17,  9, 13, 15, 13, 10, 14,
        1,  8, 13,  7, 15,  4,  7,  1, 10, 14, 17,  0, 15, 16,  5,  0, 15,
       15,  5, 16, 11, 13,  9, 13, 15,  0,  5,  5, 10, 13,  5,  5, 15,  1,
        5, 10, 14,  9,  5,  2,  8, 13, 14, 16,  5,  5,  2,  5,  9, 14,  5,
        5,  5,  2, 10, 15, 17,  5, 11, 16,  1,  9, 10,  5,  5, 13, 17, 16,
       16, 12, 17, 10,  2,  5,  5,  0, 17, 10,  1, 14,  2,  5, 13, 17,  8,
       13,  2,  1, 13,  7,  5,  5, 17,  5,  9,  5,  5,  5,  5,  5, 15,  5,
       17,  5,  5,  9, 16, 10,  5,  0,  5,  5,  5,  5,  5, 10,  5,  5,  5,
        5,  5,  5,  5,  5,  5, 10, 13,  0,  9,  9, 16, 10,  5, 17,  9,  5,
        0, 15,  0, 17,  9,  5, 10, 10,  5,  2,  1,  5, 14,  9,  5, 10, 13,
       13,  9,  5,  1,  5, 13,  2,  0,  8,  8,  7,  1, 16, 10,  1,  2, 15,
       15,  0, 14,  9,  2,  4, 15, 16, 10, 11, 10,  1,  9,  2,  5, 10,  5,
        5, 13,  5,  5,  6, 15,  7, 17,  1,  9,  9, 14, 10,  5,  8,  5, 15,
        1,  8, 10,  1,  5,  5, 16, 17,  5, 17,  5,  1, 13,  5,  1, 17,  7,
       13, 10,  1, 13, 10, 10,  5, 16,  5, 17, 17, 10, 17, 16,  5,  5,  9,
       10,  5, 17, 12, 10,  1, 10, 10,  9, 17,  0,  5, 13,  1,  1, 11, 10,
       11,  5, 16,  5,  5, 16, 13, 17,  5, 16, 10,  1,  5,  5,  5, 10, 11,
       17,  9,  5,  5, 10,  5, 13, 16, 10, 11, 13, 16, 10,  5,  4,  4,  5,
        0,  1,  9, 13, 11,  2, 17,  3,  1,  5,  9,  2, 16,  1, 13, 10, 14,
        8, 17,  5,  5,  1,  5, 14,  5,  1, 14, 13, 16, 10, 10,  5,  1, 15,
       10,  5, 17,  5,  7,  1, 15, 14, 16,  0,  1, 14,  5, 16,  9, 13, 15,
       10,  5,  0, 10,  1,  1,  5, 13, 16,  9,  1,  9, 16,  5, 10, 16, 13,
        1, 11,  5,  5,  5,  5,  8, 11,  4,  1, 17,  5, 13,  0,  5,  9,  2,
       10, 10,  0,  0,  0,  4,  6, 15, 10, 14,  5,  9, 12,  0,  0, 12, 15,
        0,  5,  4,  8, 15,  8, 10,  1, 13,  9,  2,  5,  1,  5, 10,  1, 13,
        8,  5,  5, 10, 13, 11, 13,  9,  9,  8,  2, 13,  5, 10, 15,  0,  9,
        8, 16,  4, 17,  9,  5,  5, 10, 17, 17,  5,  7, 16,  5,  9,  4, 17,
        8,  9, 17,  0,  1, 15,  9, 17, 15, 15,  9, 14,  5, 15,  0,  5,  5,
        1, 10, 15, 15,  5,  9,  6, 14, 16,  0,  9,  8,  5,  5,  6,  1,  7,
        4,  5, 13,  8,  5,  5,  6])

In [30]:
pred_1 = svc1.predict(X_vec[-500:])
pred_2 = svc2.predict(X_vec[-500:])

In [31]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(pred_1, y1_le[-500:]))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.95      0.95      0.95        40
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00         1
           4       0.91      1.00      0.95        10
           5       0.89      0.99      0.94       110
           6       1.00      1.00      1.00         7
           7       1.00      1.00      1.00        10
           8       0.94      1.00      0.97        16
           9       0.97      0.95      0.96        40
          10       0.98      0.94      0.96        54
          11       1.00      1.00      1.00        11
          12       0.75      0.75      0.75         4
          13       1.00      0.95      0.97        39
          14       0.94      1.00      0.97        16
          15       0.93      1.00      0.96        26
          16       0.97      0.69      0.81        42
          17       1.00      0.97      0.98        33

    accuracy                           0.95       500
   macro avg       0.96      0.96      0.95       500
weighted avg       0.95      0.95      0.95       500

In [33]:
print(classification_report(pred_2, y2_le[-500:]))

              precision    recall  f1-score   support

           0       0.95      0.67      0.78        30
           1       0.86      0.83      0.84        23
           2       0.97      0.99      0.98       447

    accuracy                           0.97       500
   macro avg       0.93      0.83      0.87       500
weighted avg       0.97      0.97      0.96       500

- Ascept 컬럼과 SentimentPolarity 컬럼의 데이터를 결합 
- LabelEncoder를 이용하여 수치로 변환 
- Kfold, Pipe, GridsearchCV를 활용
- 계층화 폴드화는 5개 
- 벡터화, 모델 학습을 파이프라인으로 생성 
- 파라미터 조합은 벡터화에서 max_features의 조합은 (3000, None)
- SVC 모델의 조합은 C 값을 (1.0, 2.0)
- 최적의 모델의 스코어를 확인

In [34]:
aspect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10467 entries, 0 to 10466
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Aspect             10467 non-null  object
 1   SentimentText      10467 non-null  object
 2   SentimentWord      10467 non-null  object
 3   SentimentPolarity  10467 non-null  object
dtypes: object(4)
memory usage: 327.2+ KB

In [35]:
aspect_df['Aspect'] + '_' +aspect_df['SentimentPolarity']

0        디자인_1
1        두께_-1
2         기능_1
3         색상_0
4        디자인_0
         ...
10462    착용감_1
10463    사이즈_1
10464    디자인_1
10465    디자인_1
10466     마감_1
Length: 10467, dtype: object

In [36]:
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline

In [37]:
X = aspect_df['SentimentText'].values
y = (aspect_df['Aspect'] + '_' + aspect_df['SentimentPolarity']).values

In [38]:
le = LabelEncoder()
y_le = le.fit_transform(y)

In [39]:
y_le

array([17, 12,  5, ..., 17, 17, 19], shape=(10467,))

In [40]:
pipe = Pipeline(
    [
        ('vector', vec), 
        ('model', svc1)
    ]
)
cv = StratifiedKFold(
    n_splits=5, shuffle=True, random_state=42
)
params = {
    'vector__max_features' : [3000, None], 
    'model__C' : [1.0, 2.0]
}

In [41]:
grid = GridSearchCV(
    estimator= pipe, 
    param_grid= params, 
    cv = cv
)

In [42]:
grid.fit(X, y_le)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_split.py:813: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('vector',
                                        TfidfVectorizer(max_df=0.8,
                                                        max_features=3000,
                                                        min_df=3,
                                                        ngram_range=(1, 2),
                                                        tokenizer=<function tokenize at 0x0000023A4B4D1640>)),
                                       ('model',
                                        LinearSVC(class_weight='balanced',
                                                  random_state=42))]),
             param_grid={'model__C': [1.0, 2.0],
                         'vector__max_features': [3000, None]})

In [43]:
grid.best_score_

np.float64(0.7412812800753501)

In [44]:
# 종속 변수를 2차원의 데이터로 그대로 활용 
X = aspect_df['SentimentText'].values
le = LabelEncoder()
aspect_df['Aspect_le'] = le.fit_transform(aspect_df['Aspect'])
aspect_df['SentimentPolarity'] = aspect_df['SentimentPolarity'].astype(int)
y = aspect_df[ ['Aspect_le', 'SentimentPolarity'] ].values

In [45]:
y.shape

(10467, 2)

In [46]:
X.shape

(10467,)

In [47]:
vec = TfidfVectorizer(
    tokenizer=tokenize, 
    ngram_range= (1,2), 
    min_df = 3, 
    max_df = 0.8, 
    lowercase= False
)

In [48]:
X_vec = vec.fit_transform(X)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [49]:
svc = LinearSVC(random_state=42, class_weight='balanced')

In [50]:
from sklearn.multioutput import MultiOutputClassifier

In [51]:
# MultiOutputClassifier는 분류모델에서 종속변수가 2차원 이상인 경우 사용하는 객체 
multi_model = MultiOutputClassifier(svc)

In [52]:
multi_model.fit(X_vec, y)

MultiOutputClassifier(estimator=LinearSVC(class_weight='balanced',
                                          random_state=42))

In [53]:
print(type(y[0][0]), type(y[0][1]))

<class 'numpy.int64'> <class 'numpy.int64'>

In [54]:
from sklearn.model_selection import KFold
cv2 = KFold(n_splits=5, random_state=42, shuffle=True)

In [55]:
# 쉬는시간에 확인 

pipe = Pipeline(
    [
        ('vector', vec),
        ('model', multi_model)
    ]
)
params = {
    'model__estimator__C' : [0.8, 1.0]
}
grid = GridSearchCV(
    estimator= pipe, 
    cv = cv2, 
    param_grid= params, 
    scoring= 'accuracy'
)

In [56]:
grid.fit(X, y)

c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 411, in accuracy_score
    y_type, y_true, y_pred, sample_weight = _check_targets(
                                            ~~~~~~~~~~~~~~^
        y_true, y_pred, sample_weight
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_classification.py", line 138, in _check_targets
    raise ValueError("{0} is not supported".format(y_type))
ValueError: multiclass-multioutput is not supported

  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:927: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 916, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 317, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ekfla\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\metrics\_scorer.py", line 417, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('vector',
                                        TfidfVectorizer(lowercase=False,
                                                        max_df=0.8, min_df=3,
                                                        ngram_range=(1, 2),
                                                        tokenizer=<function tokenize at 0x0000023A4B4D1640>)),
                                       ('model',
                                        MultiOutputClassifier(estimator=LinearSVC(class_weight='balanced',
                                                                                  random_state=42)))]),
             param_grid={'model__estimator__C': [0.8, 1.0]},
             scoring='accuracy')

In [57]:
pred = multi_model.predict(X_vec[-20:])

In [58]:
pred

array([[ 5,  1],
       [ 9,  1],
       [ 6,  1],
       [14,  1],
       [16,  1],
       [ 0,  1],
       [ 9,  1],
       [ 8,  1],
       [ 5, -1],
       [ 5,  1],
       [ 6, -1],
       [ 1,  1],
       [ 7,  1],
       [ 4,  1],
       [ 5,  1],
       [13,  1],
       [ 8,  1],
       [ 5,  1],
       [ 5,  1],
       [ 6,  1]])

In [59]:
pred_df = pd.DataFrame(
    pred, columns = ['aspect', 'polarity']
)
pred_df['text'] = X[-20:]

In [60]:
pred_df['aspect'] = le.inverse_transform(pred_df['aspect'])

In [61]:
pred_df

   aspect  polarity                                  text
0     디자인         1                       디자인이 너무너무 예쁩니다.
1      색상         1                   색상도 고급스러워서 마음에 들구요.
2      마감         1                   바느질도 꼼꼼하게 잘 되어 있어요.
3      촉감         1                       털 감촉도 아주 부드러워요~
4       핏         1                  입어 보면 핏이 더 예쁜 자켓이예요~
5      가격         1                   가격 대비 가성비 좋은 제품이예요~
6      색상         1                              색상도 좋구요~
7     사이즈         1                  모자 크기도 적당해서 마음에 들어요.
8     디자인        -1            모자가 있다 보니 밍크 특유의 올드함이 없네요.
9     디자인         1                          디자인 마음에 들어요.
10     마감        -1                      이음새가 좀 넓은 곳이 있지만
11     기능         1  얇은 목 폴라 입고 입으면 따뜻하고 포근한 느낌에 기분이 좋아요.
12     무게         1                      이 옷은 무게가 참 가벼워요.
13     두께         1                  봄가을에 입기가 딱 좋은 두께입니다.
14    디자인         1      디자인도 플리츠가 전체적으로 앞,뒤로 들어가서 멋스러워요.
15    착용감         1                     훌렁훌렁 편하게 입기가 좋아요.
16    사이즈         1                 입어보니 후드가 작지 않아서 좋았어요.
17    디자인         1                플리츠라서 고급스러우면서도 어려보이네요.
18    디자인         1          밑으로 내려갈수록 넓어지는 디자인이 마음에 들어요.
19     마감         1                       바느질도 잘 되어 있답니다~

In [62]:
# 긴 문단을 문장 별로 나눠주기 위해 Kkma로드 
from konlpy.tag import Kkma

In [63]:
kkma = Kkma()

In [64]:
file_list = glob("./test/*.json")
file_list

['./test\\1-1.여성의류(1).json',
 './test\\1-1.여성의류(2).json',
 './test\\1-1.여성의류(3).json']

In [65]:
test_df = pd.DataFrame()

for file in file_list:
    df = pd.read_json(file)
    test_df = pd.concat( [test_df, df], axis=0 )

test_df.reset_index(drop=True, inplace=True)
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            300 non-null    int64
 1   RawText          300 non-null    object
 2   Source           300 non-null    object
 3   Domain           300 non-null    object
 4   MainCategory     300 non-null    object
 5   ProductName      300 non-null    object
 6   ReviewScore      300 non-null    int64
 7   Syllable         300 non-null    int64
 8   Word             300 non-null    int64
 9   RDate            300 non-null    int64
 10  GeneralPolarity  298 non-null    float64
 11  Aspects          300 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 28.3+ KB

In [66]:
sample_text = test_df.loc[12, 'RawText']
sample_text

'털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고  하루입고벗었더니 겨드랑이같은곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도없이 손에 털뭉치???? 들이 묻어나서 포기했습니다 이게불량인가요 왜이렇게 만드신건가요 옷디자인은 너무맘에드는데 털빠짐때매 옷이아니네여'

In [67]:
# sample_text를 문장별로 나눠준다. 
text_list = kkma.sentences(sample_text)
text_list

['털이 엄청나게 빠집니다',
 '면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도 없이 손에 털 뭉치???? 들이 묻어나서 포기했습니다',
 '이게 불량인가요',
 '왜 이렇게 만드신 건가요',
 '옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여']

In [68]:
# text_list를 벡터화  -> 모델을 이용하여 예측

In [69]:
pred = grid.predict(text_list)

In [70]:
pred

array([[16,  1],
       [15, -1],
       [15, -1],
       [ 2,  1],
       [ 5,  1]])

In [71]:
pred_df = pd.DataFrame(pred, columns = ['aspect', 'polarity'])
pred_df['text'] = text_list

pred_df

   aspect  polarity                                               text
0      16         1                                       털이 엄청나게 빠집니다
1      15        -1  면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...
2      15        -1                                           이게 불량인가요
3       2         1                                      왜 이렇게 만드신 건가요
4       5         1                옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여

In [72]:
pred_df['aspect'] = le.inverse_transform(pred_df['aspect'])
pred_df

  aspect  polarity                                               text
0      핏         1                                       털이 엄청나게 빠집니다
1     품질        -1  면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...
2     품질        -1                                           이게 불량인가요
3     길이         1                                      왜 이렇게 만드신 건가요
4    디자인         1                옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여

In [73]:
pred_df['RawText'] = sample_text
pred_df

,aspect,polarity,text,RawText
0,핏,1,털이 엄청나게 빠집니다,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
1,품질,-1,면 바바리에 엄청나게 묻어나고 하루 입고 벗었더니 겨드랑이 같은 곳도 엄청 뭉처있니...,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
2,품질,-1,이게 불량인가요,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
3,길이,1,왜 이렇게 만드신 건가요,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...
4,디자인,1,옷 디자인은 너무 맘에 드는데 털 빠짐 때 매 옷이 아니 네 여,털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고 하루입고벗었더니 겨드랑이같은...

In [74]:
# test_df에서 RawText의 데이터들을 문장 별로 나눠준다. 
# raw_list 리뷰 문단을 문장으로 나눈 리스트를 담기 위한 공간 
raw_list = []
# raw_dict 리뷰 문단마다 index를 키 값으로 value는 리뷰 문단 
raw_dict = {}
for i in range(len(test_df)):
    raw_list.append(
        kkma.sentences(
            test_df.loc[i, 'RawText']
        )
    )
    raw_dict[i] = test_df.loc[i, 'RawText']

In [75]:
raw_dict

{0: '가격이 착하고 디자인이 예쁩니다',
 1: '싸고  디자인이 예뻐요. . 정말  가성비 가심비 입니다',
 2: '편하고  디자인이 예뻐요  가격도  좋아요   시원해요  빨리 마르고  이것만  입게되요',
 3: '너무 착한가격에 감사합니다 윈하는 색은 없지만',
 4: '가격이  너무 좋아서  블랙 구매했습니다  그런데 소재도  맘에  들어  흰색도  구매했습니다',
 5: '외출할때 입기에는 재질도 디자인도 좀~그러네요 그냥 집에서 편하게 입을수는 있을것 같아요',
 6: '특히 자켓이 넘작고 짧으네요. 상의는 좀작구 바지는 잘맞아요.',
 7: '싸고품질이좋아요ᆢ사이즈는좀큰듯하구요ᆢ반사이즈는내려서주문하심좋을듯해요',
 8: '바지가 너무 편하고 좋아요 티셔츠는 여름에 잘 입을 듯 베스트는 디자인은 별로지만 가격이 착해서 만족',
 9: '디자인이 예뻐요. 사이즈 잘 맞습니다.',
 10: '사이즈 딱 맞구요.  너무 예쁘고  얇지도 두껍지도 않으네요.',
 11: '저렴하게 구입해서 겨울에 잘 입을거 같아요',
 12: '털이 엄청나게 빠집니다 면 바바리에 엄청나게 묻어나고  하루입고벗었더니 겨드랑이같은곳도 엄청 뭉처있니에요 그래서 세탁을 했더니 끝도없이 손에 털뭉치???? 들이 묻어나서 포기했습니다 이게불량인가요 왜이렇게 만드신건가요 옷디자인은 너무맘에드는데 털빠짐때매 옷이아니네여',
 13: '디자인이 여성스러운 분위기가 납니다 구겨져와서 다림질 필요했어요',
 14: '99사이즈 입는데 88 사이즈 잘맞고~ 기장이 살짝 짧은듯 하지만 밝은색도 있고~ 까실까실하니 좋으네요~',
 15: '4종 마음에 들어요 색깔도 이쁘고 여름니트 입니다',
 16: '색상이 예쁘고  구김이없어요',
 17: '색상 디자인 예쁘고 맘에들어요',
 18: '가성비 갑입니다 가로패턴이라 더커 보이면 어쩌나 싶었는데 칼라고 디자인이고 다 만족합니다  가슴도  좀있는편이라  걱정했는데 핏이 괸찮아요  비치지 않아서 하나만 입고 다녀도될만 합니다',
 19: '오 좋아요 이가격에 득템 했네요 살이쪄서 고민이었는데 어지간히 커버도 되고 가볍고 시원할듯 해요 잘 입을께요 바로 세탁하느라 시착만 해서 사진은 스크린샷 으로 대체해요 사진하고 똑 같으니 걱정마세요 추천 합니다',
 20: '가격대비 최고예요 가볍고 좋아요',
 21: '그레이상의는 비침이 약간있지만 가격대비 짱이에요.  상의는래이온인데 마재질 느낌입니다',
 22: '싸게 잘샀어요~ 여름내 시원하게 잘입었습니다.',
 23: '너~~무 얇고 후들후들.이런건 팔지마세요. 색상도 별로네요.',
 24: '구김이 심하고 상의는 66사이즈 시켰는데 기존 규격보다 너무 커서 못 입고 있어요ㅠ',
 25: '가볍고 촉감이 부드러워 잘 입고있습니다',
 26: '편하고 간편하게 입을 수 있어서  좋아요 네이비로 구매했는데 셔츠와 바지가 색이 조금  달라서 별점 하나 뺐어요',
 27: '사이즈  딱 맞고  디자인도 이쁘고 ~! 최고!!~~ 강추합니다',
 28: '재질은 까칠하고 바지는 핏이 별로 임',
 29: '바지 약간 비침있어요.. 구김가는 레이온이고..그렇게 각잡힌옷이 아니라서 다림질해야하고 축축 쳐지는 느낌..뭐 가격대비 입을만은 해요',
 30: '소재,디자인도 좋아요 사이즈가 좀 큰듯해서 핑크로 작은사이즈를 구매할까했는데 품절인듯해서 그레이로 재구매 했어요  좋은 상품 저렴하게 구매해서 좋아요',
 31: '네이비 입어보고 착한가격에 좋은품질에 재구매 합니다',
 32: '소재가 인견 100% 라 촉감이 부드럽고 시원합니다  디자인도 예쁘고 다 달라 좋습니다  다만 레드와 블루는 목선이 좁아 입을때 조금 불편합니다  뒤집어 보니 주머니 한쪽면이 오버룩 처리가 안되어 완성도가 완벽하지는 않은듯 하네요 모두 주머니가 있어 활용도가 좋습니다  타사보다 가격이 비싸지만 쿠폰 적립금 사용하여 저렴하게 구입했습니다  잘 입겠습니다 ~^^',
 33: '가성비 최고~^^ 시원하고 디자인도 좋아요',
 34: '시원하고 디자인이 넘 예뻐요 자꾸입게되요',
 35: '시원하고 길이도 적당해요.',
 36: '생각보다 원단이 좋네요 부드럽고 색감도좋아요 편하네요',
 37: '디자인도 색상도 모두마음에듭니다~  시원할거같아요',
 38: '이렇게 디자인 좋은 옷이 이렇게 싸다니 오자마자 입었는데. 정말 기가막히네요. 내가 입고찍어서   이모양이지만 진짜 좋아요. 강추',
 39: '박시하게 해볼려고 일부로 한사쥬 크게 주문했어요.  40대이고 키작고 땅땅한 체형입니다.  까만색읏 외출복으로도 괜찮고 파란색 빨간색은 라운지웨어로 입어야할듯 천은 좋은편이에요.  주머니도 있고요.  가성비로 치면 만족합니다.',
 40: '너무 싸서 기대안했는데 디자인 넘  이뻐요~~',
 41: '너무 맘에듭니다 인견옷은 처음 구매한건데 저는 좋네요 디자인도 두께감도 크기도 너무 잘 맞아서 추천하고 싶어요',
 42: '가격도저렴하고 이뻐서 언니한테 선물로보냈는데 넘얇아서 집에서 편하게입는다고하네요~',
 43: '소재가 가볍고 색상도 산뜻하니 아주 좋아요.',
 44: '매우 만족합니다~ 시원하고 몽에 붙지않아 좋아요~~',
 45: 'OOO 인견원피스 구매후 디자인이 예쁜 듯해 구매했는데 길이가 주황색 원피스는 많이 짧네요 그래도 다양한 디자인 좋아요~♡',
 46: '핏은 제가 살이쪄서 55반은 되는거같은데 55주문했더니 레드가 좀 더 여유있고  블루도 편한편이예요~ 한사이즈 업해서 입으면 핏이 안 이쁠거같아요.. 레드 세탁했더니 마감 올 살짝 풀림ㅜ 암튼 원단이 너무 좋아서 별 5개 아깝지않네요~^^',
 47: '그냥 집에서나 입어야할듯 편하긴한데 이쁨은 별루',
 48: '저렴하게 구매잘했어요. 하지만 한옷바느질상태가 좋지않아 기분이별로. 반품하기귀찮아 손좀봐 입네요.',
 49: '데일리 티셔츠로 아주 편하게 잘 입고 있습니다 원단이   피부에도 좋고 촉감이 좋습니다',
 50: '엄마가 디자인을 좋아해요 얇지만 괜찮아요',
 51: '소재도 좋고 맘에 꼭 들어요 입어보니 시원하고 편안해요',
 52: '품질좋고 가격좋고 득템했네요',
 53: '배송은 괜찮은데 색이 생각보다 노란끼?누런색이라 놀랬어요 ㅜㅜ  입어보니 괜찮은 듯 하긴 하지만 색상이 썩 맘에 들진 않아요 ㅜㅜ 색 고민 후 선택하세요~',
 54: '제품저렴하고 이뻐요 소재도 좋앙ᆢ',
 55: '저렴한 가격에 득템입니다. M사이즈는 100~105중간쯤으로 잘 맞습니다.',
 56: '저렴한 가격에  행사할때 더 싸게 구매해서 너무 맘에 들어요',
 57: '약간 이염되서 왔는데 그냥 입으려고요  입어보니 핏이 이쁘긴 하네영',
 58: '얇은 니트티 싸이즈는좋은데 몸에닿았을때  따가운감이 있네요',
 59: '생각보다 얇고 촉감이 약간 깔깔해요',
 60: '얇아서 입기좋아요. 가격대비 대만족입니다. 감촉도 좋고 디자인도 괜찮아요',
 61: '얇은데 입어보니 꽤 포근해요. 재질도 부들부들한게 감촉도 괘안구 디자인도 심심하지 않게 포인트 있어서 좋네요.',
 62: '색감도 굿 가격도 굿입니다',
 63: '잘 입고 있어요. 따뜻하고 착용감이 편합니다',
 64: '보들보들 넘 좋아요.. 이가격에 3벌이나.. 진짜 최고..',
 65: '금액이   저렴해도 기대를  했었는데  그  갑어치밖에  안되는군요  그만큼만    입겠습니다',
 66: '추위타는 딸아이가 따뜻하고 목이   답답하지 않다고 잘입고 있어요~~~^^',
 67: '부들부들 포근하고 가볍고 따뜻해요 색상도 다 맘에 드네요',
 68: '너무 따뜻하고 색깔도 이쁘고 다 만족합니다 감사합니다 잘입을께요',
 69: '부클니트 따뜻하고 촉감이 부드러워요 보풀이 일어나지  않았으면 좋겠어요',
 70: '싸이즈 없어서 안사려다큰사이즈로 구매하라는 쇼호스트님말믿고 샀는데 너무 크네요 특히 갈색은 목이 너무 커서 이상해보여요 보풀도 많이나고',
 71: '길이감 엉덩이 덮여 괜춘. 젤 큰 싸이즈여서인지 팔길이가 길고 통이 넓어 별하나 뺌. 가격대비 마음에 듬.',
 72: '목부분 디자인이  어저쩡 사이즈없어서 젤큰사이즈 주문 길이는짧고 품은 겁나큰...',
 73: '셋다정말좋아요.전한단계내려와서주문했지만늘어난까바서.잘맞아요.부드럽고.강추..',
 74: '라이브방송보고 샀네요 66없어 77했는데 오버핏으로 좋네요. 드라이크리닝하라하는데 그냥울샴푸해서 입었는데 괜찮네요',
 75: '가격이 착해서 구매하기도 했는데 소프트라는 이름답게 부드럽고 편안하네요~ 색상도 차분하니 다 좋아하는거라 맘에 듭니다~',
 76: '옷이많이크네요.감촉이 많이 까끌거려요',
 77: '생객보다 신축성 덜해서 목이 끼어요',
 78: '잘늘어나서 편하고 부드러움 드라이크리닝 해야하는것이 아쉬움',
 79: '부드럽고 넉넉한 핏 맘에들며 무엇보다도 가성비가 좋아요~~^^기대 이상입니다~~.',
 80: '잘받았습니다  넉넉하게 입을려고 크게 주문했어요 따뜻합니다 보풀은 잘 생기겠네요',
 81: '사이즈 없어서 (쇼호스트분99착용보고)차라리 루즈하게 크게 입을려고 99. 구입.  큰사이즈도 나쁘지 않아요~~가격생각하면 만족 합니다~~검정이 젤 맘에 들어요~~',
 82: '배송도빠르고 옷도 넘 따뜻하고 포근하네요 가격도 착해서 넘잘산거 같아요  사이즈도 넉넉하고 편안하고 좋아요',
 83: '디자인도 틀리고 여러가지 색상으로 저렴하게 사서 잘입고있어요~~^^',
 84: '저렴하게 구매했지만 잘 입을것 같아요 모두 다른 디자인이라 더 좋으네요',
 85: '저렴하게 잘구매했구여.조끼까지  올겨울은 요아이 하나로 입어야 겠네요',
 86: '어디에나 잘 어울리고 따뜻하고 부드러워요^^ 가격대비 완전 만족 입니다',
 87: '목둘레가 좀 좁아 조심히 다뤄야합니다 색상 맘에들고 특히 밍크 부분이 맘에 들고 따뜻합니다',
 88: '넥라인을 밍크로 둘러 따뜻해보이고 하나로도 갖춰 입은듯 좋습니다 뒷목 연결부분이 약합니다 옷걸이에서 빼다가 터져서 꿰매느라 힘들었습니다 ',
 89: '가성비좋아요~ 편하게 걸치기 좋고 색감도 좋네요 제사이즈 강추!!',
 90: '아주 만족스럽네요. 두께는 얇아요 소재도 원하던 느낌이구요 기계세탁되서  너무좋습니다. 그리고 코튼이라 안끌거림 없습니다.  굿굿',
 91: '95가 매진이라서 한사이즈크걱 주문했더니 크긴큰데  크게입어서 괜찬아요~~  면이라서 촉감도좋고  늘어지지않을것같아요~~  만족합니다.',
 92: '베이지 구매해서 편안하게 잘입었고 블랙이 예뻐서 재구매 합니다',
 93: '가격이 맘에들어 주문했더니 옷 디자인이 더 맘에 들어 좋네요.따듯하고 피부에 닿는 느낌도 부드러워요.아쉬운건 치수가 약간 작은지 팔 길이 약간 작네요.한치수 크게 주문하면 될듯하네요.',
 94: '가격대비 품질은 좋아요~ 패팅 주머니가 뚫려서 온거 말고는 만족합니다.',
 95: '가격대비 훌륭합니다  조끼만 다른분들 상품평처럼 좀 싼티는나지만 그래도 잘 입을듯요 득템했네요',
 96: '가격대비 넘넘 맘에 들어요 특히 기모가  있어서. 외출복으로도 좋아요 ',
 97: '의류안에 기모가아닌베로아로되어서더욱따뜻함니다저렴한가격으로구매해서더욱좋아요타방송보다훨씬저렴함니다단지색상이품절된것이있어서아쉬웠음니다',
 98: '티와  바진ㄷㄴ  따듯  하겠고  질도  좋은데  베스트는  생각보다는 도톰하고  자크없이 똑딱이고ㅜㅜ 가슴둘레가 좀  작게 나와  잠그지  안고  입어야  겠어요  낚시 갈때   입으려구요   일상 생활복으로  좋을듯  싶어요',
 99: '작년에 그레이로 잘 입고 오트밀로 색상바꿔 주문해봤어요 옷이 넘 편해서 자주 손가입었어요 대신 니트재질이라보니 보풀감은 어쩔수업머요ㅠㅠ',
 100: '사이즈가 작아도 너무 작아요.77사이즈가 55정도밖에 안되는듯...반품비가 너무비싸 장롱행.',
 101: '색상도  다양하고 저렴해서 구매 했습니다.   가을엔  실외복으로  착용해  즐겨입었고 겨울엔  실내에서   아주  편안하게  잘   입고  있습니다.',
 102: '소재가좋아요입기편하고요엄마사드리고좋아서저도추가주문했네요 편해서홈웨어로너무좋네요~~*추천해드려요',
 103: '가격이 너무 저렴해서 기대를 안했는데 바느질처리도 잘되어있고 디자인도 정말 맘에 들어요^^',
 104: '빠른 배송 감사드려요. 옷이 부드럽고 색상도 이뻐요. 여유있는 핏이에요..',
 105: '가성비 갑입니다.  디자인도 이쁘고 길이도 적당히 짧지 않아서 더 좋았어요.  아들이 엄마의 쇼핑 노하우가 대단하다고 난리에요  아주 만족하고 적극 추천합니다',
 106: '봄ㆍ가을 편하게잘빕을수있겠네요 소제가차가운소제라 쌀쌀한날씨에인어로',
 107: '네개가 모두 디자인이 달라서, 혼자 입어도 좋고, 가족이나 친구들과 나눠 입어도 될듯해요. 회색이랑 핑크는 아랫단쪽이 좀 많이 넓어요. 저는 양옆을 좀 찝어서 동생 줬더니 아주 좋아라 합니다. 저렴한 가격에 아주 만족합니다. 편하게 잘 입을것 같아요',
 108: '컬러도 예쁘고 디자인도 예쁘고 품질도 좋아요',
 109: '가격도 좋고 상품평이 좋아서 구매했는데 생각했던 거보다 더 퀄리티가 좋아요. 이월된 옷이라 저렴한건지... 할인을 많이 해주셔서 소비자로선 좋네요. 사이즈랑 색상 모두 맘에 들어요. 오랜만에 득템했네요. 고민하시는 분들 망설이지말고 주문하세요~~',
 110: '편하게 입을 수 있으며, 사이즈는 66입는데 55선택했는데  작지 않아요. 옷감이 부드러워요.',
 111: '너무 저렴해서 기대안했는데  네가지컬러 다 괜찮아요. 신축성, 길이감 다 적당하고 이가격에 완젼득템했네요. 너무 좋아요~~',
 112: '편하게 입을수 있네요 소재가 지금 간절기 옷이예요 가격대비 가성비 좋습니다  감사합니다',
 113: '구성품도 다르고 티셔츠2개는 목부분 엉망으로 만들었네요~싸게 판다고 품질이 걍엉망이네요~상품평좋아서 구매했는데 품질이 영 엉망이네요',
 114: '까끌거린다는 평이 있어서 각오하고 주문했는데 저는 민감하지 않은 편이라 감촉은 괜찮았어요. 핏은 적당하고 색상구성이 마음에 들었어요. 봄 가을 겨울 이너로 편하게 입을 수 있는 전천후 아이템이네요.',
 115: '옷마다 사이즈가 약간씩 틀린거 같네요  목이 타이트하게 들어가는옷도 있고  촉감이 거스릴 정도는아닌거 같은데 오래입음 어찌될지 모르겠네요 사이즈가 한가지라 그냥 구매했는데  날씬하신분들이 입은 괜찮을꺼같은데 전체적으로 꽉껴서 반품하려다 일단 입어보기로 했네요',
 116: '디자인은 만족하나 소재가 넘 거칠어 목이 가려워요',
 117: '살짝 껄끄럽네요 부드러운게 아니네요 그걸말고는 가격도 싸고 배송도 빠르고 감사해요',
 118: '감촉도 좋고 모양도 맘에 들어 따뜻하고 예쁜핏으로 입을 수 있어 기분좋으네요~^^',
 119: '사이즈가 작아요 옷 마다 길이 차이도 있구요 원단도 까슬거려서 맨살에는 어렵구요 곰팡이 냄새 같은게 나요  반품하고 싶어요',
 120: '디자인과 가격대가 넘 맘에 들어 샀는데 넘 까슬거려 입기 넘 불편하네요 ㅠㅠ',
 121: '제품을 2017년도에 만든거네요~ 어차피 집에서 편하게 입으려고 구매한 것이니 크게 상관은 없어요 그러나 까슬거려서 맨살에는 NO! 어쨌든 저렴하게 구매했어요',
 122: '두껍지 않고 목이 올라와 있어서  아우터 안에 입기 딱 좋습니다 ㅡ조금 춥다싶으면 스카프로 멋을 내세요^^* 가성비 좋습니다(맨살에 입기에 약간 까슬하지만 괜찮아요)',
 123: '맨살에는 가슬가슬해요 ㅠ 디자인 사이즈는 넘 좋구요',
 124: '가격대비 너무 만족스러운 제품입니다. 네가지 제품이 특색이 달라 요즈음 골라입는 재미가 좋습니다.',
 125: '싸서 구매했는데 절대 모델핏나지 않아요  제품서 비린 냄새가 나는데 만든지 한참된 옷이네요ㅜ 편하게 입을것 같지도 읺고  반품도 어렵네요ㅜㅜ',
 126: '싸서 구매 했더니 너무 까슬거려서 입기가 별로예요ㅜㅜ',
 127: '맨살엔 깔끄럽고 요즘 입기엔 앞목이 답답해요.소재 색상 디자인 특히 값이 싸서 구입했는데 추천은 못 마겠네요.',
 128: '한철입을거 생각하고 샀어요..품질이 생각보다 괜찮네요..제일 큰 사이즈 구매했는데 사이즈가 크게 나오진 않았습니다..',
 129: '목둘레가 너무 작아서 입구 벗기가 완전 불편해요..저렴한 가격이여서 엄청난 컬리티를 원한건 아니지만..입을수가 없네요',
 130: '기계세탁하니 보풀이 생기네요 집에서 입는걸루 그래도 저렴하니 잘 입을께요',
 131: '넉넉하게 나왔구요 편하게 막 입을수있는 길이감도 적당합니다',
 132: '빠른 배송 감사드려요. 촉감이 부드럽고 색상이 넘 이뻐요. 핏은 여유있어 편하고 좋아요',
 133: '가성비 최고!! 적당한 두께에 지금시기에 딱맞는 옷이에요 왠만한 상의 1벌가격에 4벌을 쟁이네요 밝은색은 엄마 입으라고 드리고 검정, 하늘색은 제가 입고! 구성이 1석2조 너무 좋네요 평소입는 사이즈로 딱좋아요^^',
 134: '가격 저렴히 넘 잘 사서 잘 입고 있어여. 완전 편하고 데일리로 딱^^',
 135: '잘구매했구요   검정색  목부분이  벌어지지않아서  못입어요.  다른것은  탄력이  있는데  ....',
 136: '디자인이 다른건 만족해요~진짜 상품평대로 검은색은  신축성이 없어 머리가 들어가질 않네요ㅎㅎ 그냥 버렸어요.. 그게 아쉬워요.',
 137: '생각보다얇지않고지그입어도괜찮네요~가격도저렴하고배송도빠르고추천합니다~',
 138: '이가격에 정말 만족합니다 소재도좋아서 따뜻할거같아요 소매가 길어서 접어입어야겠어요 다른색도있으면 색깔별로 사고싶네요',
 139: '블랙과 레드  티셔츠에 목부분에 올이 풀려  있네요  95사이즈입는데 100으로 시켰는데도 품이 넉넉하지 않아요   소매는 좀마니 길구요 교환을 할까 반품을할까 고민중입ㄴㄱ다',
 140: '잘 입을것 같군요  3종류 디자인이 달라서 이뻐요 니트도 운동할때 괜찬아요',
 141: '상품 만족합니다  실측싸이즈가 좀 애매해서 문의드렸더니 평소입는 싸이즈로 주문하라고해서 주문했는데 잘 맞습니다. 쫀쫀한 니트재질이고 길이감도 좋아요 비싼 브랜드 한장도 안되는 가격으로 무려 3장이나 얻었네요 보풀이 나는 재질도 아닌것같은데... 디자인도 색상도 젊어서 굿굿입니다! 겨울 라운딩이 기대됩니다 착용 샷도 한번 올려보겠습니다 적극 추천합니다',
 142: '옷 핏이 너무 예뻐요 골프치는분께 추천하고 싶네요 가격도 저렴하고 재질도 좋아요 홈쇼핑에서 이런 골프핏은 첨인거같앙ᆢㄷ 잘입을게요 감사합니다',
 143: '주변에서 마니 구입했는지 연습장에 같은 옷이 또 있네요~^^ 품질은 양호. 정사이즈. 스판성은그리 좋진않고 드라이라 해야하니 가성비는 별루에요. ',
 144: '빨간색옷을 먼저입고 스크린한번 쳣죠ᆢ옷은 약간 두텁고좋은데ᆢ 팔은 길고 몸쪽으로 쫌 짧은듯합니다ᆢ제가 살이 쪄서 그런가?ᆢ싶어서  집에있는 볼빅옷이랑 비교하니 ᆢ길이가 약간 차이가 납니다 ㅋㅋᆢ좀 길면 좋는데ᆢ제 체형때문일까? 일단 ᆢ검정색이 품질이 최고 좋아보이고 ᆢ다른옷들도 좋습니다',
 145: '일단 받아보니 디자인은 조금 촌스러워요 옷은 기대 이상으로 따뜻합니다 편하고 막입기 좋아요',
 146: '좋은가격에 3종이라  감사히 입으려했으나  본의아니게 볼때마다 화가나서 글 남깁니다ㆍ 빨간색 티는 소매 밑단이 터지고 실밥이 거의 누더기상태로 포장되어왔더군요ㆍ어이없는 새옷요ㆍ 반품포장하다가 그냥  포기했네요ㆍ 믿을만한 00쇼핑을 통해 알만한 브랜드를 구매했는데 실망스럽습니다ㆍ ',
 147: '색상도 예쁘고 좋아요,  감촉이 매끄러운게 좋고 짜임이 쫀쫀하니, 좋아요~',
 148: '사이즈가 각각 다르네요 .한치수 크게 주문하라고 했는데  레드는  맞는데  2가지는 크네요ㅠㅠ  반품을 해야할지 레드는 색상이 예뻐요 .소매길이는 좀긴편입니다',
 149: '촉감이 너무좋네요 가격대비 완벽한 상품이예요 근데...한치수 크게사야 좋을듯해보여요',
 150: '싸이즈 딱 조아요  핏도 컬러도 예쁩니다.  팔이 좀길어요.',
 151: '착용하니 사이즈,핏 좋아요 디자인 맘에들어서 많이 입을거같애요',
 152: '부드러운 니트느낌입니다 사이즈는 조금 타이트하게 나온것 같고 디자인이 이쁘네요',
 153: '그냥 가격이저렴해서 샀는데 따뜻해보이는데 소재는 별로   싼티가 나네요.. 누구 주기도 그렇고..',
 154: '편하게 입기에 좋네요 소제는 별로지만 가격에 비해 괜찮은것같아요',
 155: '일단 저렴한  상품가에 호기심으로 구매하였습니다. 생각보다 착용감이 좋았고 보온성이  뛰어나고 옷 매무새도  마음에 들었습니다. 강추입니다.',
 156: '재질이 별로여요 그치만 넉넉한 품 땜에 입기로 해ㅛ어요',
 157: '가성비 갑입니다 포장도 정성스럽네요 그리고 따끗한데 소재는 쫌..',
 158: '두번째 구매입니다.  소재는 별로지만 따뜻하고 체형커버되는 디자인에 가성비가 너무 좋아요. 제 사이즈보다 한치수 내려 입어도 여유있어요.',
 159: '커도 너무 크구요. 소재도, 두껍지도, 부드럽지도, 글쎄 반품이 여의치 않아 그냥 두었습니다.',
 160: '겨울 내내 지금까지도 잘 입고 있어요 세탁도 편하고  가격대비 색상도 다야애서 대체로 만족해요',
 161: '사이즈가 넘크게 나와서 맘에않들어요 66입어서 구입했는데 88같은사이즈에 깜놀 교환하고싶은데 교환비가 6천원 배보다배꼽이크네요 저렴해서 구입했건만 속상하넹ᆢㄷ',
 162: '재질은 얇고 부드러워요 세탁기 돌려도 줄거나 변형없구요 몸통은 풍덩해서 편하고 좋은데 팔뚝은 여유없이 꽉 끼어서 입고있으면 좀 답답하고 불편해요..심지어 가오리 스탈이라.. 어깨선도 뭔가 옷을 앞뒤 반대로 입은것처럼 어딘가 불편해요',
 163: '가볍고 따뜻해요 다만 목부분이 많이 느슨해서 많이 추운날에는 목도리를 꼭 해야겠네요',
 164: '반짝이원단이 생각보다 많아요 편하게 입기좋고 사이즈 넉넉해요',
 165: '66을햇는데도 목부분이너무쪼입니다.사진상은 여유로운스탈같아서  구매한건데...잡아늘리고있네요ㅋ저렴해서 패스입니다.',
 166: '두껍지 않으면서  부드럽고 따뜻한데 맨살에 입어도 아무렇지도 않아요. 자켓 이너로 좋겠어요. 이런 가격에 이정도라니  완전 가성비 갑입니다.',
 167: '색상 질감 다 맘에듭니다 신축성도 좋아 입고 벗기 편합니다',
 168: '두껍지 않아서 레이어드 하기 좋아요. 반짝이가 과하지 않고 은은함. 정사이즈로 입으면 되고 길이는 힙을 덮을 정도는 아님',
 169: '가격대비 상품의 질이 너무 좋아요 보들보들 해서 잘 하고다닐것같아요',
 170: '흘러내리듯 매우 부드럽고  착용감이 좋고 따뜻하네요',
 171: '상품의 만족도  good!  소장의가치도  goood! 따뜻하고  부드럽고  아무렇게나  둘러도 멋스럽고 색상도 이쁩니다.',
 172: '레깅스에 입으려 한치수크게샀는데 많이 길진안아요 저렴히 잘샀습니다. ',
 173: '싼값에 반품은 안해요..팔길이가 3종 모두 달라요.ㅜㅜ 줄차로 재 봤더니 3센치나 차이나네요',
 174: '두껍지도 얇지도  적당한 기모  고급지진 않지만 편하게 입을수 있을것 같아요.',
 175: '디자인도 예쁜 정말 나무랄때 없는 좋은 상품 이예요~ 살짝 아쉬움이 있다면 색상 밝은 컬러를 하나쯤 더 있었으면 좋았을것 같아요~',
 176: '잘받았습니다  약품냄새가 심하네요 옷은 따뜻하고 착용감은 편합니다',
 177: '빠른 배송 감사하고 가격 저렴하게 잘 구입했어요^^ 품질도 좋고 사이즈도 넉넉하고 따뜻해요 코트안에 입으니 너무 좋으네요',
 178: '팔기장이 잘안맞아서 늘 좀 짧은듯 입었는데 이상품은 팔기장도 알맞게 길고 품도 적당하게 떨어져서 맘에 들어요 싼가격에 잘샀어요',
 179: '루즈핏이네요~ 적당한두께~얇은기모~따뜻하겠어요 가격이 너무 착해요~ㅎㅎ',
 180: '가성비는 좋은데..색감도 훌륭 이뻐요 입었을때도 핏이 엄청 이뻐요..제가 찾던 옷입니다',
 181: '색상도이쁘고두루두루잘입을거같아요',
 182: '저렴한데 이쁘네요. 편하게 잘 입고 다닐 수 있겠어요. 약간 까칠거리긴해요',
 183: '가격대비 정말 좋은 상품입니다. 재질도 좋고 디자인도 예쁘네요.',
 184: '재질도 너무 따갑고 사이즈도 작게 나와 입을수가 없네요ㅜ 금액이 저렴해서 반품 않고 누구 주고 싶어도 촉감이 너무 따가워 줘도 욕먹을거같아서 주지도 못하고 그냥 반품해야 할거 같네요ㅜ',
 185: '가격대비 너무 좋은 상품입니다. 1+1  최곱니다. 딸아이 입고 넘 좋아합니다. 사이즈 큰거 미리 추가주문합니다.',
 186: '기대없이 주문했는데 품질이 완전괜찮은 옷이네요~ 원닥 톡톡하구 안에는 기모처리되어있구 완전 괜찮은 옷입니다^^',
 187: '남편도   착용감이 편하다 하고   간절기  입기좋아해요',
 188: '따뜻하고 좋은제품, 가성비도 좋네요~',
 189: '질이 좋아요 좀 늘어지긴 하는데 괜찮아요 편하게 입을것같아요',
 190: '화면보다 색상이 더 좋아요 그리고 사이즈도 잘 맞네요.',
 191: '핏이 이쁩니다. 혹시나  중고생 딸들에게 입을래? 하며 물어보니...한개씩 챙기네요.. 엉덩이 살짝 가려주고 짜임이 이뻐 올봄에 잘입을것 같습니다. 생각보다 핑크가 화사해서 많이 입을것 같습니다. 색상 다 이쁩니다.',
 192: '옷 자체는 예쁘지만 너무 느슨하고 니트가 꼼꼼하지 못하고 힘이 없어요 그리고 세가지중 한색은 옷 사이즈가 완전 작아요  귀찮아 그냥 입을려고요',
 193: '디자인이 이뻐요 소매길이도 길고 날씬해보이고 색상도 이뻐요 딸이랑 나눠입으려  입었어요',
 194: '3종 다 색상도 이쁘고 디자인도 좋은데 사이즈가 크게 나왔어요 어깨선도 내려오고 품이 너무 커요.',
 195: '개봉시 냄새가 많이 나요 옷 품질은 좋아요',
 196: '색상도 이쁘고 디자인도 좋은데 어깨선이 넘 오버핏이네요.품도 넘 크고.., 싸이즈 하나 줄여 재 주문합니다. 그 정도로 다른건 다 맘에들어요 사이즈 넉넉하니 정사이즈 추천합니다~^^ 참고로 두께감이 있어 날씬해보여요~',
 197: '통통66  여유있게 맞아요 따뜻하고 디자인이 예쁘네요',
 198: '조카딸아이가 코랄핑크가 맘에든다고 하여 구매했는데 오늘 받고 바로 입어보네요  색상이 넘 맘에 든대요  나머지 두가지 색은 제가 입기로 했습니다^^ 보통 66사이즈입는데 90사이즈도 조금 여유있게 잘 맞네요   사이즈 크게 나왔나봅니다',
 199: '일단은 택이 네이비색 옷에만 있어요~ 옷상태를 봐서도 왠지 반품물건 느낌에 기분이 좀 그렇더라구요.   원단은 괜찮은 느낌이구 디자인은 많이 박시하고 롱합니다. 참고로 160cm 55사이즈 구입했구요. 키가 좀 크신 분들에겐 괜찮을 듯 합니다.  조금 실망스럽지만 반품 귀찮아 입으려고요.',
 200: '가격대비 만족스러워요. 한 가지 아쉬운 점은 55로 주문했는데, 티셔츠 사이즈가 제 각각이네요. 같은 55로 보내주신 것 같은데 ..ㅠㅠ 그래서 좀 넉넉하게 나온 것은 엄마 두려요~~',
 201: '디자인, 색상 다 맘에 들어요. 세탁후 모양변형과  보풀만 잘 안생기면 좋겠어요.',
 202: '제질도좋고 사이즈도잘맞고.따뜻하니 너무좋아요',
 203: '디잔인 무난해서 데일리룩으로 입기 좋아요 팔이 총기장 대비 쫌 긴것 같아서 아쉽네요',
 204: '품질은 그런데로 괜찮은데 좀앏아서  봄에나 날이 따뜻해지먼 입어야할거같아요~',
 205: '가성비짱!! 색상이 너무 맘에들고 디자인도 이뻐요 ~~',
 206: '간절기입기딱좋아요 재질도괜찮고66사이즈딱맞네요ㅋ엉덩이길이소매 길이도이쁘고전목도안답답하고좋으네요',
 207: '재질이 넘 좋아요  보풀이 날것 같지 않아요 그러면서도 부드럽고 몸에 착 감기는게 너무 예쁩니다',
 208: '옷을 입었을때 촉감도 부드럽고 목을 반정도 감싸 주니 따뜻하고 몸에 살짝 붙는것 같아 보이지만 여유감도 있고 예뻐요~~',
 209: '44사이즈가 55붙는사이즈네요~ 저는 카라있는게  제일 예쁘고 두께감도 괜찮구요 그외 블랙, 회색, 레드은 약간 얇고 진짜 이너로 입기에는 괜찮은고거같은데...레드가 좀 얇은감이 입고 사이즈가  아주 조금씩 차이납니다 가격대비 만족합니다!!!',
 210: '아가타 홈쇼핑에 방송하는거치고 받아보니 싼티가 넘 많이 나네요 그냥 싼 맛에 입을라고 이가격에 3개면 그냥 입을만하니간요',
 211: '가격대비 편하고 예쁘네요. 골프옷보다는 평상시 요즘 날씨에 딱 입기 좋은것같아요. 3종 모두 맘에 듭니다. 잘 입을께요. ',
 212: '가격대비 괜찮아요 편하게 입기는 좋은데 기존 아가타 보다는 소재가 좀 검은색은 애매하고 타이트 하네요',
 213: '옷이 예쁘고 핏도좋고  소매가 조금 깅어요 잘입늘께요',
 214: '엄청 고급스럽진 않고, 그냥 무난합니다. 청바지랑 같이 입기 편하겠어요. 단추나 장식 박음질이 꼼꼼하지 않고 많이 덜렁대서 한번 다시 박음질 해야겠어요. 그래도 튀지 않고  여기저기 편하게 잘 입을 거 같아 구매합니다.',
 215: '니트하나하나다~디자인이 이쁘네요~착용감도편하고.싸이즈도정싸이즈라이뻐요~',
 216: '상품평없어서 별 기대없이 주문햇는데 배송도 빠르고 재질도 따뜻할거같아 좋네요 보풀걱정이 되긴하지만 조심히입어야죠 머...',
 217: '색상선택  앞두고 한참 고민했는데^^ 핑크.와인  배색도 좋고  화면보다 색상이 더 예뻐요. 한사이즈 크게 했더니 더 좋은것같아요.  ',
 218: '원단이 부드럽고 실용적입니다',
 219: '시어머님 선물로 사드렸는데 너무 너무 마음에 드셔하네요.니트지만 안에 얇은 기모 처리가 되어 있어 따뜻하니 바람도 안들어 올꺼 같다며 좋아하셔요ㅎㅎ ',
 220: '서이즈는 잘맞는데 소매랑 옆구리부분이 한번입었는데도 보풀이 많이 생겼어요. 품질이 좀 아쉬워요',
 221: '사이즈도 딱 맞고 정말 따뜻해요. 디자인도 예뻐서 색깔별로 돌아가며 계속 입고 있어요. 자켓도 예쁘고 따뜻합니다.',
 222: '바람막이 자켓은 괜찮은데 티셔츠는 뭔가 불편하고 부피감이 있어 실물보다 살쪄 보입니다. 품질이나 원단으로만 보면 괜찮은 편입니다.',
 223: '사이즈며 너무 좋습니다 보기보다 두툼하여 추위걱정은 없을꺼같구요 다만 팔길이가 조금길어 살짝아쉽정도네요',
 224: '자켓은생각보다얇은편이었고.3종티셔츠는 .품질이 가격만큼이네여ㅠㅠ.저렴한가격에.막입긴좋을듯요',
 225: '가격대비 퀄리티도 좋고 보온성 완젼좋아요. 피부에 닿는느낌 또한 너무 포근합니다.',
 226: '나이드니 살집이 많아져서 빅사이즈  골프웨어 찾기 힘들고, OOO 니트는 사이즈가 안성맞춤 이네요.  추울때 제외하고는 티셔츠입고 착용해도 무난해요. 봄.가을 초겨울에도 착용 가능해요',
 227: '쟈켓은 생각보다 조금얇지만 티셔츠는 도톰하서 따뜻하니 좋아요~~',
 228: '이동수골프 니트스윙자켓 바람막이가 기모의 따뜻함을 보호해주니 더욱 따뜻하고 포근합니다. 저렴한가격에 제품의 만족감까지 대만족입니다.',
 229: '가격은저렴한데 구성에서 니트티는 싼티가나요 바람막이때문에 구입했으니 다른건 사은품정도로생각하고입으려구요 입어보니 보풀때문에 못입을정도네요 반품은어렵다고하고 보풀제거기가고장날정도로 보풀뜯어가며입는데 곧버려야할꺼같아요 상품이불량인듯 제품전체가불량인듯해요',
 230: '디자인도 좋고 품질이 가격대비너무좋아요~~언니에게선물해주었는데너무좋다고극찬을해주네요',
 231: '색깔 디자인은 괜찮은데 옷감질이 좀 그렇네요',
 232: '비싼돈주고 이동수 골프웨어민 구입했었는데 싸고 질좋은것을 질선택했습니다. 맘에 들어요.',
 233: '따뜻하고 디자인이 예쁜거 저렴하게 잘사서 아주 잘입고 다닙니다',
 234: '상품 받아 확인하니 디자인이 깔끔하고 심플해서 만족입니다 가격대비 구성도 좋고요',
 235: '가디건은얇은듯 하고  약간 크고 티는 생각보다 두꺼워서 따뜻하게 입을수 있을듯 해요 ',
 236: '레드 이쁘네요  티셔츠 목부분이신축성이없어서 머리큰사람은 엄청힘드네요 .... 그래도 저렴하고 좋으네요',
 237: '자켓 디자인이 가장 맘에 들구요, 기모티셔츠도 활용도가 높네요~♡',
 238: '며칠 입은것도 아니고 하루 입었는데 티세츠에 보풀이 심하네요 살짝 라인도 있으면 좋겠는데 박스스타일에 천이 엉 아니에요~~ 입으면 너무 보기싫어요',
 239: '부드럽고 감촉어  좋아요 핏이  좋아서 색상과 조화롭네요',
 240: '넉넉한 길이가 우선 맘에 들고요 가볍고 따뜻해서 자주 입고 있어요.',
 241: '촉감좋고 사이즈 딱이예요 기모가 들어서 한겨울에도 든든할것같구요 그런데 봉제선 라인이 투박해서 어깨라인이 각져보이고 빨간색티는 목이 늘어나지않아 입기가 매~우 불편해요 전체적으로 스판이 조금부족해서 활동하기 불편한듯해요 딱  가격만큼의 가치인듯해요',
 242: '티셔츠는 정말 품질이 아니네요 신축성도없고 타이트해요 답답 하구요',
 243: '제품 디자인이 아주 깔끔하고 고급스러워요',
 244: '친정아빠주문해드렸는데 티셔츠가 가볍고 따뜻하고 좋아하시네요',
 245: '사이즈도 정사이즈, 스타일도 좋고 오랫만에 득템하였습니다',
 246: '날씬하게  보이고 싸게잘구입했어요  감사합니다 ㅡ',
 247: '디자인 품질 가격 모두 만족합니다~',
 248: '가격도 착하고 입은 모습도 이뻐서 좋아요. 옷감이 좀더 부드러우면 좋을 것 같아요.',
 249: '재질도 두껍고 루즈 핏이면 자칫 뚱뚱해 보일수 있는데 날씬해 보입니다.  ',
 250: '재질도 두툼하고 착용감이 편해요 특히 바지가 완전 편합니다ㅎㅎ',
 251: 'ㅣ잘받았구요  가디건이 넘 펑퍼짐해서 뚱뚱해보이는데 목도리로 사용하니 좋은것같아 그냥 입으려구요  가격대비 착해서요 ',
 252: '아주 저렴하게 편하고  색상도 맘에들어요',
 253: '셔츠가 보풀이 좀 생기네요 가디건은 가성비 좋네요',
 254: '핏이 너무예뻐요 디자인이 세련되고편리하게여러모로잘코디가됩니다 좋은상품감사드려요 좋은가격에 좋은품질넘감사드려요 잘 유용하게입고있어요',
 255: '니트도 적당한 길이감에 소재도 나쁘지 않구요  판쵸 숄가디건은 편하게 걸치기 좋고 은근 따뜻해요 ㅎㅎ  가성비 최고 상품 같아요^^',
 256: '간절기에 필요한 제품이고 예쁘기까지하네요.',
 257: '간절기입기에너무좋네요 두께가 좋아서요 만족합니다 ',
 258: '약간 크게나와 딱 맞게 입으려면 한사이즈 작게 입어도 좋을것 같네요 색상및 디자인 맘에 드네요 가격대비 재질은 좋아요 숄만가지고도 봄까지 유용하게 입을것 같아요',
 259: '따뜻하고  디자인도  고급스럽고  가성비  최고야요',
 260: '안에니트티 색상은  화면과달리 연한핑크라 더 맘에드네요 타홈쇼핑에서 7 만원대에 방송했는데 정말 가격이착하네요 사이즈도여유있고 괜찮은 제품입니다    정말가격착하네요 ',
 261: '색상이 예쁘게 나왔어요. 키가 커서인지 길이는 조금 짧네요. 분위기가 나서 좋아요.',
 262: '제품의 색상은 만족하나 정사이즈에비해 큽니다            ',
 263: '포근하고 입고벗기간편하면 무엇보다 활용도가 좋아요어떤  옷에도 매치하기좋은 물건입니다',
 264: 'ㅇㅇ쇼핑에서 첨으로 구매했어요!니트티는 좀 얇아서 봄 가을에 입으려구요 판쵸는 아이보리보다 블랙니트티에 입으니 디자인이 더 고급스럽고 멋스럽네요! 저렴한가격으로 맘에 드는옷샀어요',
 265: '날씬한사람에겐 예쁠것같은데 저에겐 좀 부 하게 보이네요 그래도 적립금으로 저렴하게 구입했습니다 잘입을께요~',
 266: '추운겨울끝날무렵이면 옷입기 애매한데 겉에 편하게 걸치고 나갈수 있을것 같아서 미리 구매했는데 길이가 엄청 맘에 드네요',
 267: '기대이상이네요 핏도 예쁘고 사이즈도 딱 좋아요',
 268: '숄가디건 하나쯤 가지고싶은 아이인데 때마침좋은옷 가지게되어 좋습니다  핏도좋고 착용감이 편하고 맘에듭니다',
 269: '소재가 그럭저럭 이네요 저렴한 딱 그가격',
 270: '블랙 색상 풀오버는 아이보리 정도 되겠지 했는데 베이지에 가까워서 다른 블랙티셔츠랑 입어야할것 같아요. 일단 디쟈인은 좋은데 원단이 가격만큼인듯 같네요ㅜㅜ',
 271: '판쵸 숄 가디건, 니트풀오버 모두 디자인은 물론 색상과 옷감의 품질이 좋고 핏도 매우 만족하여 다른 색상으로 한세트 더 주문하고 싶은 마음이네요.',
 272: '가성비 좋고, 입었을때핏도 맘에 들고 다른옷과도 코디가 잘되서 맘에 들어요. 지인에게 추천 했어요 ',
 273: '구성맘에들어요~디자인이 체형커버도되구요.가디건으로여러활용할수있네요..잘입을께요',
 274: '가성비 짱입니다!! 니트 촉감도 좋아요~~',
 275: '봄이 되면 간절기에 편하게 입고 일할수있는 편리성과 각각 옷을 다양하게 코디하기에 좋을듯합니다 티는 간단히 입고 다른옷에 코디가 가능하고 ᆢ윗 옷은 어떤 색깔과도 잘 맞아  멋낼 때 입을수 있는 코디형 스카프 같은 느낌입니다 ᆢ잘입을께요',
 276: '소재가 너무 고급지고 편하고 핏더 멋스럽네요~',
 277: '디자인이 예뻐서 직장 동료가 바로 두개 더 구매 합니다.  네이비도  디자인이 무난하고 안에 입는 쉐터도 넉넉하고 좋아요.가격대비 좋은 상품으로 득템했어요.',
 278: '멋지게 코디해서 잘 입고 있어요 친구들이 다들 이쁘다고 해요 디자인도 이쁘다고 해요',
 279: '아무색에도받쳐입기편하고거실에서등쌀쌀할때잘입어요',
 280: '덩치가 있어 판쵸는 어울리지않았는데 전혀 안 뚱해보이고 이쁘네요 재질도 나쁘지않고 안에 다른 목티를 입어도 어울려요',
 281: '화면엔 살짝 밝은 보랏빛이 이뻐서 주문 했는데 실물로는 보랏빛 하나도 없는 그냥 네이비 네요 색상만 불만족 이고 상품은 디자인이 좋아요',
 282: '가격대비 만족 케이프 목돌이도 되구 좋아요',
 283: '가격대비 만족감100입니다ㅋ 따뜻하고 디자인도 멋지고 색모두 만족~~^^',
 284: '착용하는데  부담이 없고  티셔스위에  부담없이  좋아요 브드럽고 소매단추가   있어   흘러내리지  앓아 운전할때  좋으네요 두깨감이  얇아도  따뜻하고  착용감 편해요',
 285: '저렴한 가격에 완전 득템요 무심하게 툭 걸쳐도 멋스럽고 실내에서 코디하기 좋네요 검수를 잘 안하셨는지 왼쪽 소맷단에 구멍이 나있네요',
 286: '판쵸랑 티랑 둘다 디자인이 맘에 들어요 겨울.봄까지 잘 입어질것 같습니다 대만족 입니다',
 287: '세일가로 구입한거라 그냥 입지만 생각보다 품질이 별루임',
 288: '목부분 둘레가 좁다고하는데 저는 괜찮네요 목부분이 늘어나서 쏙들어가더라고요 롱베스트니트 세트 디자인 좋아요 저렴한가격으로 사이즈넉넉하고 좋아요 길이도 괜찮고요 코트속에 입어도 좋네요 ',
 289: '사이즈가 조금 크게 나온것 같아요 편한하게 잘입을 수 있겠어요',
 290: '이렇게 먼지 많이 묻어온 소재의 니트는 첨예요..좀 털어서 입어도 계속 먼지는 묻네요.좋아하는 디자인이라 겟하지만 재질이 좀 아쉽네요.',
 291: '길이며 품이며 다 좋아요..품질이 고급지진않지만 가격대비 완젼만족요',
 292: '화면에서는 오렌지가 쨍한 밝은색인줄알았는데 갈색에가까운 오렌지 색상이네요 그냥저냥 입으려구요 가디건보다 이너가 입고 다니기 더 괜찮은듯요~',
 293: '검정색 털이 아주그냥 어마어마하게 빠져서 다른옷에 코디할수가 없어요.  세탁햇는데 몇번이나 검은 털빠진 물이 ㅠㅠㅠ.    속니트도 따가워서 못입겟고.  세탁햇느니 반품은 안될거고. 암튼 다신 안입을거 같아요.',
 294: '티셔츠 가 조금 크긴하지만 가격대비 좋으네요  ',
 295: '품질은 살짝 별루지만 핏은 좋아요',
 296: '가볍고 젊어보이고 디자인이 이쁨니다 가성비최고! 잘입을께요~^^',
 297: '니트는 전체적으로 푸대자루 디자인인데, 목둘레는 너무 작고 신축성 없어서 (머리가 작은편인데도)입기 힘듬. 입고 있는 동안 목 조이는 느낌이 듬.. 몸통은 상당히 박시함.  베스트 디자인은 맘에 들어서 베스트만 입기로.',
 298: '55입는데 사이즈가 너무크고 재질이 너무 까슬거려서 잘 안입게되네요...',
 299: '지금 날씨에 입기 딱 좋은 두께에요. 어깨까지 덮어주니 따뜻하니 좋아요. 사이즈도 넉넉해서 크지 않게 주문하는게 좋아요. 색상도 예쁘게 잘 나왔어요.'}

In [76]:
# raw_list
sentence_df = pd.DataFrame()
for idx, raw in enumerate(raw_list):
    pred = grid.predict(raw)
    temp_df = pd.DataFrame(pred, columns = ['Pred_Aspect', 'Pred_Polarity'])
    # raw_dict의 idx의 값은 해당 예측 값의 문단
    temp_df['sentence_text'] = raw
    temp_df['RawText'] = raw_dict[idx]
    # temp_df는 하나의 리뷰에 대한 예측 값들
    # print(temp_df)
    # break
    # 나온 데이터프레임을 sentence_df에 단순 행 결합 
    sentence_df = pd.concat( [sentence_df, temp_df], axis=0 )
sentence_df.reset_index(drop=True, inplace=True)

In [77]:
sentence_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Pred_Aspect    707 non-null    int64
 1   Pred_Polarity  707 non-null    int64
 2   sentence_text  707 non-null    object
 3   RawText        707 non-null    object
dtypes: int64(2), object(2)
memory usage: 22.2+ KB

In [78]:
sentence_df.head(10)

,Pred_Aspect,Pred_Polarity,sentence_text,RawText
0,5,1,가격이 착하고 디자인이 예쁩니다,가격이 착하고 디자인이 예쁩니다
1,5,1,싸고 디자인이 예뻐요. .,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다
2,16,1,정말 가 성비 가심 비 입니다,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다
3,5,1,편하고 디자인이 예뻐요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
4,0,1,가격도 좋아요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
5,15,1,시 원해요 빨리 마르고 이것만 입게 되요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
6,0,1,너무 착한 가격에 감사합니다,너무 착한가격에 감사합니다 윈하는 색은 없지만
7,5,-1,윈하는 색은 없지만,너무 착한가격에 감사합니다 윈하는 색은 없지만
8,0,1,가격이 너무 좋아서 블랙 구매했습니다,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...
9,10,-1,그런데 소재도 맘에 들어 흰색도 구매했습니다,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...

In [79]:
sentence_df['Pred_Aspect'] = le.inverse_transform(sentence_df['Pred_Aspect'])

In [80]:
sentence_df.head(10)

,Pred_Aspect,Pred_Polarity,sentence_text,RawText
0,디자인,1,가격이 착하고 디자인이 예쁩니다,가격이 착하고 디자인이 예쁩니다
1,디자인,1,싸고 디자인이 예뻐요. .,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다
2,핏,1,정말 가 성비 가심 비 입니다,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다
3,디자인,1,편하고 디자인이 예뻐요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
4,가격,1,가격도 좋아요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
5,품질,1,시 원해요 빨리 마르고 이것만 입게 되요,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요
6,가격,1,너무 착한 가격에 감사합니다,너무 착한가격에 감사합니다 윈하는 색은 없지만
7,디자인,-1,윈하는 색은 없지만,너무 착한가격에 감사합니다 윈하는 색은 없지만
8,가격,1,가격이 너무 좋아서 블랙 구매했습니다,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...
9,소재,-1,그런데 소재도 맘에 들어 흰색도 구매했습니다,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...

In [81]:
# test_df와 sentence_df을 조인 결합 
# (test_df와 sentence_df의 RawText는 같은 집합 -> 4개의 종류는 모두 같은 결과가 나온다.)
len(
    pd.merge( test_df, sentence_df, on = 'RawText', how='outer' )
)

707

In [82]:
df = pd.merge(test_df, sentence_df, on = 'RawText', how='inner')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            707 non-null    int64
 1   RawText          707 non-null    object
 2   Source           707 non-null    object
 3   Domain           707 non-null    object
 4   MainCategory     707 non-null    object
 5   ProductName      707 non-null    object
 6   ReviewScore      707 non-null    int64
 7   Syllable         707 non-null    int64
 8   Word             707 non-null    int64
 9   RDate            707 non-null    int64
 10  GeneralPolarity  701 non-null    float64
 11  Aspects          707 non-null    object
 12  Pred_Aspect      707 non-null    object
 13  Pred_Polarity    707 non-null    int64
 14  sentence_text    707 non-null    object
dtypes: float64(1), int64(6), object(8)
memory usage: 83.0+ KB

In [84]:
df.head(10)

,Index,RawText,Source,Domain,MainCategory,ProductName,ReviewScore,Syllable,Word,RDate,GeneralPolarity,Aspects,Pred_Aspect,Pred_Polarity,sentence_text
0,7,가격이 착하고 디자인이 예쁩니다,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,17,4,20210815,1.0,"[{'Aspect': '가격', 'SentimentText': '가격이 착하고', ...",디자인,1,가격이 착하고 디자인이 예쁩니다
1,9,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,31,8,20210807,1.0,"[{'Aspect': '가격', 'SentimentText': '싸고', 'Sent...",디자인,1,싸고 디자인이 예뻐요. .
2,9,싸고 디자인이 예뻐요. . 정말 가성비 가심비 입니다,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,31,8,20210807,1.0,"[{'Aspect': '가격', 'SentimentText': '싸고', 'Sent...",핏,1,정말 가 성비 가심 비 입니다
3,15,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,49,10,20210804,1.0,"[{'Aspect': '착용감', 'SentimentText': '편하고', 'Se...",디자인,1,편하고 디자인이 예뻐요
4,15,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,49,10,20210804,1.0,"[{'Aspect': '착용감', 'SentimentText': '편하고', 'Se...",가격,1,가격도 좋아요
5,15,편하고 디자인이 예뻐요 가격도 좋아요 시원해요 빨리 마르고 이것만 입게되요,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,49,10,20210804,1.0,"[{'Aspect': '착용감', 'SentimentText': '편하고', 'Se...",품질,1,시 원해요 빨리 마르고 이것만 입게 되요
6,17,너무 착한가격에 감사합니다 윈하는 색은 없지만,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,25,6,20210803,1.0,"[{'Aspect': '가격', 'SentimentText': '너무 착한가격에 감...",가격,1,너무 착한 가격에 감사합니다
7,17,너무 착한가격에 감사합니다 윈하는 색은 없지만,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,25,6,20210803,1.0,"[{'Aspect': '가격', 'SentimentText': '너무 착한가격에 감...",디자인,-1,윈하는 색은 없지만
8,18,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,52,11,20210717,1.0,"[{'Aspect': '가격', 'SentimentText': '가격이 너무 좋아...",가격,1,가격이 너무 좋아서 블랙 구매했습니다
9,18,가격이 너무 좋아서 블랙 구매했습니다 그런데 소재도 맘에 들어 흰색도 ...,쇼핑몰,패션,여성의류,OO 플** 베스트 풀코디 3종,100,52,11,20210717,1.0,"[{'Aspect': '가격', 'SentimentText': '가격이 너무 좋아...",소재,-1,그런데 소재도 맘에 들어 흰색도 구매했습니다

In [85]:
# ProductName의 고유 값들을 확인 
df['ProductName'].unique()

array(['OO 플** 베스트 풀코디 3종', 'OO 여성 소프트 진주 아** 니트 2종 택1',
       'OO 크** 긴팔 니트 티셔츠 베이지', 'OO 샤** 썸머 쿨니트 4종', 'OO 레** 카라 상하세트 3종 택1',
       'OO 여성 인견 원피스 3종세트', 'OO 여성 시** 실크코튼 티셔츠 4종 세트',
       'OO 클** 카라 반팔티셔츠 12종 택1', 'OO 울블랜디드 여성 니트 3종', 'OO 라** 니트 4종세트',
       'OO 웜 소프트 부** 니트 3종세트', 'OO 여성 밍** 캐시미어 니트 4종 택1', 'OO 여성 니트 3종',
       'OO 니트 라** 세트', 'OO 스** 티셔츠 4종세트', 'OO 울블랜디드 니트 4종 세트',
       'OO 스** 케이블 니트 풀오버 4종세트', 'OO 레이어드 풀오버 4종 세트', 'OO 여성 골프니트3종',
       'OO 기모 니트 4종세트', 'OO 캐시미어코튼 글** 니트 3종 택1', 'OO 니트숄',
       'OO 기모 풀오버 3종 SET ', 'OO 남녀 겨** 니트 골프웨어 골프복 4종세트', 'OO 모** 니트 2종',
       'OO 여성 호** 혼방 풀오버 1+1 2종세트', 'OO 여성 기모 맨투맨티셔츠 1+1 2종세트',
       'OO 봄 케이블니트 니트 3종', 'OO 봄 여성 케이블니트 니트 3종', 'OO 스프링 니트블라우스 3종',
       'OO 스프링 니트 블라우스 3종_리뉴얼', 'OO 여성 패딩자켓+티셔츠3종',
       '블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터)', 'OO 스** 니트블라우스 4종',
       '여성 OO 시** 가을 코튼니트 3종', 'OO 캐시미어 블** 숄가디건',
       'OO 여성 하** 웜웨어 스웨터 4종세트', 'OO 여성 자켓+니트티셔츠 3종',
       'OO 여성 니트자켓+니트티셔츠 총 4종', 'OO 니트자켓+니트티셔츠 총 4종', 'OO 루** 니트 셋업 세트',
       'OO 울 블** 롱베스트+ 니트 풀오버 세트'], dtype=object)

In [86]:
product_df = df.loc[
    df['ProductName'] == 'OO 플** 베스트 풀코디 3종'
]

In [87]:
# Pred_Aspect 컬럼으로 그룹화를 하고 Pred_Polarity 의 평균 
product_df[['Pred_Aspect', 'Pred_Polarity']].groupby('Pred_Aspect').mean()

             Pred_Polarity
Pred_Aspect
가격                1.000000
디자인               0.200000
사이즈              -0.333333
소재               -1.000000
착용감               1.000000
품질                1.000000
핏                 1.000000

In [93]:
# df에서 그룹화를 ProdictName, Pred_Aspect기준으로 그룹화를 하고 Pred_Polarity 의 평균 
df[ ['ProductName', 'Pred_Aspect', 'Pred_Polarity'] ]\
    .groupby(['ProductName', 'Pred_Aspect']).mean().unstack()

                                Pred_Polarity                                \
Pred_Aspect                                가격        기능        길이   냄새   두께
ProductName
OO 기모 니트 4종세트                        0.666667  1.000000       NaN  NaN  1.0
OO 기모 풀오버 3종 SET                     1.000000       NaN  1.000000 -1.0  1.0
OO 남녀 겨** 니트 골프웨어 골프복 4종세트                NaN       NaN       NaN  NaN  NaN
OO 니트 라** 세트                         1.000000       NaN -1.000000  NaN  NaN
OO 니트숄                               1.000000       NaN       NaN  NaN  NaN
OO 니트자켓+니트티셔츠 총 4종                        NaN       NaN       NaN  NaN  NaN
OO 라** 니트 4종세트                            NaN       NaN       NaN  NaN  NaN
OO 레** 카라 상하세트 3종 택1                 1.000000  1.000000       NaN  NaN  1.0
OO 레이어드 풀오버 4종 세트                    0.600000       NaN  1.000000  NaN  1.0
OO 루** 니트 셋업 세트                      1.000000       NaN       NaN  NaN  NaN
OO 모** 니트 2종                              NaN       NaN       NaN  NaN  NaN
OO 봄 여성 케이블니트 니트 3종                       NaN  1.000000  1.000000  NaN  0.5
OO 봄 케이블니트 니트 3종                     1.000000       NaN       NaN  NaN  NaN
OO 샤** 썸머 쿨니트 4종                     1.000000       NaN       NaN  NaN  NaN
OO 스** 니트블라우스 4종                     1.000000       NaN  1.000000  NaN  1.0
OO 스** 케이블 니트 풀오버 4종세트               1.000000       NaN       NaN  NaN  NaN
OO 스** 티셔츠 4종세트                      1.000000  0.333333  1.000000  NaN  NaN
OO 스프링 니트 블라우스 3종_리뉴얼                     NaN       NaN       NaN  NaN  NaN
OO 스프링 니트블라우스 3종                     1.000000  1.000000       NaN  NaN  NaN
OO 여성 골프니트3종                         0.333333  1.000000 -0.666667  NaN  NaN
OO 여성 기모 맨투맨티셔츠 1+1 2종세트                  NaN       NaN       NaN  NaN  NaN
OO 여성 니트 3종                               NaN  1.000000       NaN  NaN  0.0
OO 여성 니트자켓+니트티셔츠 총 4종                0.400000  1.000000  0.000000  NaN -1.0
OO 여성 밍** 캐시미어 니트 4종 택1              1.000000  1.000000  0.000000  NaN  NaN
OO 여성 소프트 진주 아** 니트 2종 택1            1.000000       NaN  1.000000  NaN  1.0
OO 여성 시** 실크코튼 티셔츠 4종 세트                  NaN  1.000000       NaN  NaN  1.0
OO 여성 인견 원피스 3종세트                    1.000000  1.000000  1.000000  NaN  NaN
OO 여성 자켓+니트티셔츠 3종                         NaN  1.000000       NaN  NaN  NaN
OO 여성 패딩자켓+티셔츠3종                          NaN       NaN -1.000000  NaN  NaN
OO 여성 하** 웜웨어 스웨터 4종세트                    NaN       NaN       NaN  NaN  NaN
OO 여성 호** 혼방 풀오버 1+1 2종세트            1.000000       NaN       NaN  NaN  NaN
OO 울 블** 롱베스트+ 니트 풀오버 세트             1.000000       NaN  0.000000  NaN  1.0
OO 울블랜디드 니트 4종 세트                    0.428571  1.000000 -1.000000 -1.0  1.0
OO 울블랜디드 여성 니트 3종                    1.000000       NaN       NaN  NaN  0.5
OO 웜 소프트 부** 니트 3종세트                 0.875000  1.000000 -1.000000  NaN  NaN
OO 캐시미어 블** 숄가디건                     1.000000  1.000000  0.000000  NaN  1.0
OO 캐시미어코튼 글** 니트 3종 택1               1.000000       NaN  0.500000  NaN  1.0
OO 크** 긴팔 니트 티셔츠 베이지                      NaN       NaN       NaN  NaN  NaN
OO 클** 카라 반팔티셔츠 12종 택1               1.000000       NaN       NaN  NaN  NaN
OO 플** 베스트 풀코디 3종                    1.000000       NaN       NaN  NaN  NaN
블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터)           NaN       NaN       NaN  NaN  NaN
여성 OO 시** 가을 코튼니트 3종                 0.666667  0.500000  1.000000  NaN  NaN

                                                                         \
Pred_Aspect                           디자인   마감   무게       사이즈        색상
ProductName
OO 기모 니트 4종세트                    1.000000  NaN  1.0 -1.000000  1.000000
OO 기모 풀오버 3종 SET                 1.000000  NaN  NaN -1.000000 -1.000000
OO 남녀 겨** 니트 골프웨어 골프복 4종세트            NaN  NaN  NaN       NaN  1.000000
OO 니트 라** 세트                     1.000000  NaN  NaN  0.000000  1.000000
OO 니트숄                                NaN  NaN  NaN       NaN  1.000000
OO 니트자켓+니트티셔츠 총 4종               1.000000  NaN  1.0  1.000000       NaN
OO 라** 니트 4종세트                        NaN  NaN  NaN       NaN -1.000000
OO 레** 카라 상하세트 3종 택1             1.000000  NaN  NaN -0.500000 -1.000000
OO 레이어드 풀오버 4종 세트                1.000000  NaN  NaN  1.000000  1.000000
OO 루** 니트 셋업 세트                       NaN  NaN  NaN       NaN       NaN
OO 모** 니트 2종                          NaN  NaN  NaN       NaN       NaN
OO 봄 여성 케이블니트 니트 3종              1.000000  NaN -1.0  0.200000  0.500000
OO 봄 케이블니트 니트 3종                      NaN  NaN  NaN  1.000000  1.000000
OO 샤** 썸머 쿨니트 4종                 1.000000  NaN  1.0  1.000000  1.000000
OO 스** 니트블라우스 4종                 1.000000  NaN  NaN  1.000000       NaN
OO 스** 케이블 니트 풀오버 4종세트                NaN  NaN  NaN -1.000000       NaN
OO 스** 티셔츠 4종세트                  1.000000 -1.0  NaN  0.666667  0.600000
OO 스프링 니트 블라우스 3종_리뉴얼            1.000000  NaN  NaN       NaN       NaN
OO 스프링 니트블라우스 3종                 1.000000  NaN  NaN  0.000000       NaN
OO 여성 골프니트3종                     0.200000 -1.0  NaN  0.000000  1.000000
OO 여성 기모 맨투맨티셔츠 1+1 2종세트              NaN  NaN  NaN       NaN       NaN
OO 여성 니트 3종                           NaN  NaN  NaN  0.000000  1.000000
OO 여성 니트자켓+니트티셔츠 총 4종            1.000000  NaN  0.0  0.000000  1.000000
OO 여성 밍** 캐시미어 니트 4종 택1               NaN  NaN  NaN -1.000000  1.000000
OO 여성 소프트 진주 아** 니트 2종 택1        1.000000  NaN  NaN  0.500000       NaN
OO 여성 시** 실크코튼 티셔츠 4종 세트         1.000000  NaN  NaN       NaN       NaN
OO 여성 인견 원피스 3종세트                0.818182 -1.0  1.0  0.500000  0.333333
OO 여성 자켓+니트티셔츠 3종                1.000000  NaN  NaN  1.000000  1.000000
OO 여성 패딩자켓+티셔츠3종                      NaN  NaN  NaN  1.000000       NaN
OO 여성 하** 웜웨어 스웨터 4종세트                NaN  NaN  NaN       NaN       NaN
OO 여성 호** 혼방 풀오버 1+1 2종세트        1.000000  NaN  NaN -0.500000       NaN
OO 울 블** 롱베스트+ 니트 풀오버 세트        -0.333333  NaN  NaN -0.500000  1.000000
OO 울블랜디드 니트 4종 세트                0.800000  NaN -1.0 -0.500000  1.000000
OO 울블랜디드 여성 니트 3종                1.000000  NaN  NaN  1.000000       NaN
OO 웜 소프트 부** 니트 3종세트             1.000000  NaN  1.0  0.000000  1.000000
OO 캐시미어 블** 숄가디건                 1.000000 -1.0  NaN  0.200000  0.750000
OO 캐시미어코튼 글** 니트 3종 택1                NaN  NaN  NaN       NaN  1.000000
OO 크** 긴팔 니트 티셔츠 베이지             1.000000  NaN  NaN       NaN       NaN
OO 클** 카라 반팔티셔츠 12종 택1                NaN  NaN  NaN  0.000000  1.000000
OO 플** 베스트 풀코디 3종                0.200000  NaN  NaN -0.333333       NaN
블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터)       NaN  NaN  NaN       NaN       NaN
여성 OO 시** 가을 코튼니트 3종             1.000000  1.0  NaN -1.000000  0.000000

                                                                              \
Pred_Aspect                            소재       신축성 제품구성       착용감        촉감
ProductName
OO 기모 니트 4종세트                   -0.500000       NaN  NaN  1.000000       NaN
OO 기모 풀오버 3종 SET                      NaN       NaN  NaN  1.000000       NaN
OO 남녀 겨** 니트 골프웨어 골프복 4종세트            NaN       NaN  NaN       NaN       NaN
OO 니트 라** 세트                     0.000000       NaN  NaN  1.000000  1.000000
OO 니트숄                                NaN       NaN  NaN  1.000000  1.000000
OO 니트자켓+니트티셔츠 총 4종                    NaN       NaN  NaN       NaN       NaN
OO 라** 니트 4종세트                        NaN       NaN  NaN       NaN       NaN
OO 레** 카라 상하세트 3종 택1            -1.000000       NaN  NaN  1.000000  1.000000
OO 레이어드 풀오버 4종 세트                     NaN -1.000000  1.0       NaN  1.000000
OO 루** 니트 셋업 세트                 -1.000000       NaN  NaN  1.000000       NaN
OO 모** 니트 2종                          NaN       NaN  NaN       NaN       NaN
OO 봄 여성 케이블니트 니트 3종                   NaN       NaN  NaN       NaN  1.000000
OO 봄 케이블니트 니트 3종                      NaN       NaN  NaN  1.000000       NaN
OO 샤** 썸머 쿨니트 4종                 1.000000       NaN  NaN       NaN       NaN
OO 스** 니트블라우스 4종                 1.000000       NaN  NaN       NaN  1.000000
OO 스** 케이블 니트 풀오버 4종세트                NaN       NaN  NaN       NaN       NaN
OO 스** 티셔츠 4종세트                  1.000000       NaN  NaN  0.833333       NaN
OO 스프링 니트 블라우스 3종_리뉴얼                 NaN       NaN  NaN       NaN       NaN
OO 스프링 니트블라우스 3종                      NaN       NaN  NaN       NaN  1.000000
OO 여성 골프니트3종                    -1.000000       NaN  NaN  1.000000  1.000000
OO 여성 기모 맨투맨티셔츠 1+1 2종세트              NaN       NaN  NaN       NaN       NaN
OO 여성 니트 3종                      1.000000       NaN  NaN  1.000000  1.000000
OO 여성 니트자켓+니트티셔츠 총 4종            1.000000  0.333333  1.0  0.000000  1.000000
OO 여성 밍** 캐시미어 니트 4종 택1          1.000000       NaN  NaN       NaN       NaN
OO 여성 소프트 진주 아** 니트 2종 택1             NaN       NaN  NaN       NaN       NaN
OO 여성 시** 실크코튼 티셔츠 4종 세트         1.000000       NaN  NaN       NaN  1.000000
OO 여성 인견 원피스 3종세트               -0.333333  0.000000  NaN  0.000000  1.000000
OO 여성 자켓+니트티셔츠 3종                0.000000       NaN  NaN       NaN       NaN
OO 여성 패딩자켓+티셔츠3종                      NaN       NaN  NaN       NaN       NaN
OO 여성 하** 웜웨어 스웨터 4종세트           1.000000       NaN  NaN       NaN       NaN
OO 여성 호** 혼방 풀오버 1+1 2종세트             NaN       NaN  NaN       NaN  0.000000
OO 울 블** 롱베스트+ 니트 풀오버 세트              NaN  1.000000  1.0  1.000000       NaN
OO 울블랜디드 니트 4종 세트                0.500000       NaN  1.0  1.000000 -0.333333
OO 울블랜디드 여성 니트 3종                     NaN       NaN  NaN       NaN -1.000000
OO 웜 소프트 부** 니트 3종세트                  NaN  0.000000  1.0  1.000000  0.500000
OO 캐시미어 블** 숄가디건                 1.000000       NaN  1.0  1.000000  1.000000
OO 캐시미어코튼 글** 니트 3종 택1          -1.000000  1.000000  NaN  1.000000       NaN
OO 크** 긴팔 니트 티셔츠 베이지                  NaN       NaN  NaN       NaN       NaN
OO 클** 카라 반팔티셔츠 12종 택1           0.000000       NaN  NaN       NaN       NaN
OO 플** 베스트 풀코디 3종               -1.000000       NaN  NaN  1.000000       NaN
블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터)       NaN       NaN  NaN       NaN       NaN
여성 OO 시** 가을 코튼니트 3종                  NaN       NaN  NaN  1.000000       NaN


Pred_Aspect                            품질         핏       활용성
ProductName
OO 기모 니트 4종세트                    1.000000  1.000000  0.000000
OO 기모 풀오버 3종 SET                 1.000000  1.000000  1.000000
OO 남녀 겨** 니트 골프웨어 골프복 4종세트            NaN  1.000000       NaN
OO 니트 라** 세트                     1.000000       NaN  1.000000
OO 니트숄                                NaN       NaN       NaN
OO 니트자켓+니트티셔츠 총 4종                    NaN       NaN       NaN
OO 라** 니트 4종세트                        NaN       NaN       NaN
OO 레** 카라 상하세트 3종 택1             1.000000  0.000000       NaN
OO 레이어드 풀오버 4종 세트                0.000000  0.500000  1.000000
OO 루** 니트 셋업 세트                  1.000000  1.000000       NaN
OO 모** 니트 2종                          NaN       NaN  1.000000
OO 봄 여성 케이블니트 니트 3종             -1.000000  1.000000       NaN
OO 봄 케이블니트 니트 3종                      NaN  1.000000       NaN
OO 샤** 썸머 쿨니트 4종                      NaN  1.000000       NaN
OO 스** 니트블라우스 4종                -1.000000  1.000000  1.000000
OO 스** 케이블 니트 풀오버 4종세트           1.000000       NaN       NaN
OO 스** 티셔츠 4종세트                  0.500000  1.000000  1.000000
OO 스프링 니트 블라우스 3종_리뉴얼           -1.000000       NaN       NaN
OO 스프링 니트블라우스 3종                -1.000000       NaN       NaN
OO 여성 골프니트3종                     1.000000  0.428571  1.000000
OO 여성 기모 맨투맨티셔츠 1+1 2종세트         1.000000  1.000000       NaN
OO 여성 니트 3종                           NaN  1.000000       NaN
OO 여성 니트자켓+니트티셔츠 총 4종            0.250000  1.000000  1.000000
OO 여성 밍** 캐시미어 니트 4종 택1               NaN  1.000000       NaN
OO 여성 소프트 진주 아** 니트 2종 택1       -1.000000  1.000000       NaN
OO 여성 시** 실크코튼 티셔츠 4종 세트         1.000000       NaN  1.000000
OO 여성 인견 원피스 3종세트                1.000000  0.600000  0.333333
OO 여성 자켓+니트티셔츠 3종               -1.000000  1.000000       NaN
OO 여성 패딩자켓+티셔츠3종                      NaN       NaN  1.000000
OO 여성 하** 웜웨어 스웨터 4종세트                NaN       NaN       NaN
OO 여성 호** 혼방 풀오버 1+1 2종세트             NaN  1.000000  1.000000
OO 울 블** 롱베스트+ 니트 풀오버 세트         0.000000  1.000000  1.000000
OO 울블랜디드 니트 4종 세트                     NaN  1.000000  1.000000
OO 울블랜디드 여성 니트 3종                     NaN       NaN       NaN
OO 웜 소프트 부** 니트 3종세트            -0.333333  0.818182  1.000000
OO 캐시미어 블** 숄가디건                -1.000000  0.846154  0.923077
OO 캐시미어코튼 글** 니트 3종 택1                NaN       NaN       NaN
OO 크** 긴팔 니트 티셔츠 베이지                  NaN       NaN       NaN
OO 클** 카라 반팔티셔츠 12종 택1                NaN  0.500000       NaN
OO 플** 베스트 풀코디 3종                1.000000  1.000000       NaN
블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터)  1.000000       NaN       NaN
여성 OO 시** 가을 코튼니트 3종                  NaN  0.666667  1.000000

In [92]:
pd.pivot_table(
    df, 
    index = 'ProductName',
    columns = 'Pred_Aspect' ,
    values = 'Pred_Polarity', 
    aggfunc= 'mean'
)

Pred_Aspect,가격,기능,길이,냄새,두께,디자인,마감,무게,사이즈,색상,소재,신축성,제품구성,착용감,촉감,품질,핏,활용성
ProductName,,,,,,,,,,,,,,,,,,
OO 기모 니트 4종세트,0.666667,1.000000,NaN,NaN,1.0,1.000000,NaN,1.0,-1.000000,1.000000,-0.500000,NaN,NaN,1.000000,NaN,1.000000,1.000000,0.000000
OO 기모 풀오버 3종 SET,1.000000,NaN,1.000000,-1.0,1.0,1.000000,NaN,NaN,-1.000000,-1.000000,NaN,NaN,NaN,1.000000,NaN,1.000000,1.000000,1.000000
OO 남녀 겨** 니트 골프웨어 골프복 4종세트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
OO 니트 라** 세트,1.000000,NaN,-1.000000,NaN,NaN,1.000000,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000
OO 니트숄,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN
OO 니트자켓+니트티셔츠 총 4종,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OO 라** 니트 4종세트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OO 레** 카라 상하세트 3종 택1,1.000000,1.000000,NaN,NaN,1.0,1.000000,NaN,NaN,-0.500000,-1.000000,-1.000000,NaN,NaN,1.000000,1.000000,1.000000,0.000000,NaN
OO 레이어드 풀오버 4종 세트,0.600000,NaN,1.000000,NaN,1.0,1.000000,NaN,NaN,1.000000,1.000000,NaN,-1.000000,1.0,NaN,1.000000,0.000000,0.500000,1.000000
OO 루** 니트 셋업 세트,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,1.000000,NaN,1.000000,1.000000,NaN
OO 모** 니트 2종,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
OO 봄 여성 케이블니트 니트 3종,NaN,1.000000,1.000000,NaN,0.5,1.000000,NaN,-1.0,0.200000,0.500000,NaN,NaN,NaN,NaN,1.000000,-1.000000,1.000000,NaN
OO 봄 케이블니트 니트 3종,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,NaN
OO 샤** 썸머 쿨니트 4종,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,1.0,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
OO 스** 니트블라우스 4종,1.000000,NaN,1.000000,NaN,1.0,1.000000,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,1.000000,-1.000000,1.000000,1.000000
OO 스** 케이블 니트 풀오버 4종세트,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
OO 스** 티셔츠 4종세트,1.000000,0.333333,1.000000,NaN,NaN,1.000000,-1.0,NaN,0.666667,0.600000,1.000000,NaN,NaN,0.833333,NaN,0.500000,1.000000,1.000000
OO 스프링 니트 블라우스 3종_리뉴얼,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN
OO 스프링 니트블라우스 3종,1.000000,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,-1.000000,NaN,NaN
OO 여성 골프니트3종,0.333333,1.000000,-0.666667,NaN,NaN,0.200000,-1.0,NaN,0.000000,1.000000,-1.000000,NaN,NaN,1.000000,1.000000,1.000000,0.428571,1.000000
OO 여성 기모 맨투맨티셔츠 1+1 2종세트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN
OO 여성 니트 3종,NaN,1.000000,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,1.000000,1.000000,NaN,1.000000,NaN
OO 여성 니트자켓+니트티셔츠 총 4종,0.400000,1.000000,0.000000,NaN,-1.0,1.000000,NaN,0.0,0.000000,1.000000,1.000000,0.333333,1.0,0.000000,1.000000,0.250000,1.000000,1.000000
OO 여성 밍** 캐시미어 니트 4종 택1,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
OO 여성 소프트 진주 아** 니트 2종 택1,1.000000,NaN,1.000000,NaN,1.0,1.000000,NaN,NaN,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN
OO 여성 시** 실크코튼 티셔츠 4종 세트,NaN,1.000000,NaN,NaN,1.0,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000
OO 여성 인견 원피스 3종세트,1.000000,1.000000,1.000000,NaN,NaN,0.818182,-1.0,1.0,0.500000,0.333333,-0.333333,0.000000,NaN,0.000000,1.000000,1.000000,0.600000,0.333333
OO 여성 자켓+니트티셔츠 3종,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN
OO 여성 패딩자켓+티셔츠3종,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
OO 여성 하** 웜웨어 스웨터 4종세트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OO 여성 호** 혼방 풀오버 1+1 2종세트,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,-0.500000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000
OO 울 블** 롱베스트+ 니트 풀오버 세트,1.000000,NaN,0.000000,NaN,1.0,-0.333333,NaN,NaN,-0.500000,1.000000,NaN,1.000000,1.0,1.000000,NaN,0.000000,1.000000,1.000000
OO 울블랜디드 니트 4종 세트,0.428571,1.000000,-1.000000,-1.0,1.0,0.800000,NaN,-1.0,-0.500000,1.000000,0.500000,NaN,1.0,1.000000,-0.333333,NaN,1.000000,1.000000
OO 울블랜디드 여성 니트 3종,1.000000,NaN,NaN,NaN,0.5,1.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN
OO 웜 소프트 부** 니트 3종세트,0.875000,1.000000,-1.000000,NaN,NaN,1.000000,NaN,1.0,0.000000,1.000000,NaN,0.000000,1.0,1.000000,0.500000,-0.333333,0.818182,1.000000
OO 캐시미어 블** 숄가디건,1.000000,1.000000,0.000000,NaN,1.0,1.000000,-1.0,NaN,0.200000,0.750000,1.000000,NaN,1.0,1.000000,1.000000,-1.000000,0.846154,0.923077
OO 캐시미어코튼 글** 니트 3종 택1,1.000000,NaN,0.500000,NaN,1.0,NaN,NaN,NaN,NaN,1.000000,-1.000000,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN
OO 크** 긴팔 니트 티셔츠 베이지,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OO 클** 카라 반팔티셔츠 12종 택1,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.500000,NaN
OO 플** 베스트 풀코디 3종,1.000000,NaN,NaN,NaN,NaN,0.200000,NaN,NaN,-0.333333,NaN,-1.000000,NaN,NaN,1.000000,NaN,1.000000,1.000000,NaN
블** 겨울 OO 마스터 컬렉션 여성 4종(니트/스웨터),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
여성 OO 시** 가을 코튼니트 3종,0.666667,0.500000,1.000000,NaN,NaN,1.000000,1.0,NaN,-1.000000,0.000000,NaN,NaN,NaN,1.000000,NaN,NaN,0.666667,1.000000