### 데이터베이스와 python의 연결 
1. 데이터베이스와 연결을 하기 위한 라이브러리 설치 
2. 라이브러리 로드 
3. 데이터베이스 서버와의 연결 
    - 서버의 정보 
        - 서버의 주소 
        - 서버의 포트(3306)
        - 아이디 (root)
        - 비밀번호 ( 비밀번호가 없으면 생략 가능 )
        - 사용할 데이터베이스명 (multicam)
4. Cursor(가상공간)를 생성
5. SQL query문을 작성하여 질의를 DB서버에 보낸다. 
    - select(조회) 
        - return 데이터가 존재 
        - fetchall() 함수를 이용해서 결과 값을 돌려받는다. 
    - insert, update, delete 
        - return 데이터가 존재x
        - 실제 데이터가 변화(Cursor변환) -> DB서버와 Cursor 동기화
7. 서버와의 연결을 종료

In [ ]:
# 라이브러리 설치 
# !pip install pymysql cryptography

In [2]:
# 라이브러리 로드 
import pymysql

In [5]:
# DB server와의 연결 
# 컴퓨터의 주소? 외부 컴퓨터 DB에 접속하려면 IP 필요
# 내 컴퓨터 DB server 주소 -> 127.0.0.1 | localhost

_db = pymysql.connect(
    # host = 'localhost',
    host = '127.0.0.1',     # 서버의 주소
    port = 3306,            # 서버의 포트(숫자로 입력)
    user = 'root',          # DB server 접속 아이디
    password = '1234',      # 비밀번호 (비밀번호가 없는 경우 생략 가능)
    db = 'multicam'         # 데이터베이스명
)

In [6]:
# 가상공간인 Cursor 생성 

# 기본값으로 커서 생성 -> select문으로 데이터를 로드할때 결과 데이터의 타입이 tuple
cursor = _db.cursor()
# DictCursor 옵션을 사용해서 커서 생성
cursor2 = _db.cursor( pymysql.cursors.DictCursor )

In [ ]:
# query문을 작성 -> 문자열 데이터로 작성 
select_query = """
    select 
    * 
    from 
    `emp`
"""
# select_query를 cursor에게 보낸다 (질의)
cursor.execute(select_query)
cursor2.execute(select_query)
# execute() 함수의 리턴은 select인 경우 인덱스의 수 출력

14

In [8]:
# cursor안에 select의 결과가 저장되어 있어서 해당 데이터를 가져온다(fetchall())
# fetchall() 함수를 호출 시 cursor의 데이터를 가져오고 cursor에 데이터는 제거 
select1 = cursor.fetchall()
select2 = cursor2.fetchall()

In [ ]:
select1

In [ ]:
select2

In [11]:
import pandas as pd

In [12]:
df1 = pd.DataFrame(select1)
df2 = pd.DataFrame(select2)

In [13]:
df1.head(1)

      0      1      2       3           4      5    6     7
0  7369  SMITH  CLERK  7902.0  1980-12-17  800.0  0.0  20.0

In [14]:
df2.head(1)

   EMPNO  ENAME    JOB     MGR    HIREDATE    SAL  COMM  DEPTNO
0   7369  SMITH  CLERK  7902.0  1980-12-17  800.0   0.0    20.0