### 데이터의 분할
- 분석 모델을 학습하고 성과를 확인하기 위해서 데이터를 Train, Test 세트로 나눠주는 작업 
- 독립 변수(X) -> 문제 , 종속 변수(y) -> 정답
- 독립 변수와 종속 변수 모두 Train, Test 데이터로 나눠준다. 
- 분석 방법이나 데이터의 양에 따라서 Train, Validation, Test로 나눠주는 경우도 발생 
- 데이터를 분할하는 일반적인 비율 
    - Train : Test = 7 : 3 // 8 : 2
        - 가장 일반적인 분할 비율
    - Train : Validation : Test = 6 : 2 : 2
        - 데이터의 양이 많은 경우 검증 셋을 생성하여 2번에 검증 작업 
    - kfold를 이용하면 여러번의 작업을 하여 검증이 가능
    - 유의할 점 
        - 데이터의 불균형 문제.
        - 데이터의 균형을 알맞게 분할하는 작업이 필요
- sklearn안에 train_test_split() 함수를 이용하여 데이터를 분할
    - train_test_split( X, y, test_size = None, random_state = None, shuffle = True, stratify = None )
        - X : 독립 변수( 문제 )
        - y : 종속 변수( 정답 )
        - test_size : 테스트데이터의 비율 (0부터 1사이의 값)
        - random_state : 임의의 데이터를 추출하는 과정에서 seed 값을 지정 (같은 값을 지정하면 규칙이 생성되어 같은 데이터를 확인)
        - shuffle : 데이터를 섞을것인가 ( 시계열 데이터셋인 경우에는 False )
        - stratify : 특정 변수를 지정하면 지정한 변수를 기준으로 하여 계층화 되어 해당 변수의 비율을 유지하도록 데이터 분할

In [1]:
import pandas as pd 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
# 샘플 데이터셋 로드 
iris_data = load_iris()

In [3]:
iris_data['frame']

In [4]:
# 데이터프레임으로 변경 
iris = pd.DataFrame(iris_data['data'], columns = iris_data['feature_names'])

# target 데이터 데이터프레임에 추가 
iris['class'] = iris_data['target']

iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
# target 데이터들을 변환 
iris['class'] = iris['class'].map(
    lambda x : iris_data['target_names'][x]
)

In [6]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [7]:
# class 컬럼의 데이터의 빈도수를 확인 
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [8]:
# 종속 변수, 독립 변수 데이터를 나눠서 train_test_splot() 입력 
x = iris.drop('class', axis=1)
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
y = iris['class']
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: class, Length: 150, dtype: object

In [10]:
# train_test_split() --> 결과물( train_x, test_x, train_y, test_y )
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size= 0.3, random_state=42
)

In [11]:
# 데이터의 개수를 확인 
print(f"X_trian : {X_train.shape}, X_test : {X_test.shape}")
print(f"y_train : {y_train.shape}, y_test : {y_test.shape}")

X_trian : (105, 4), X_test : (45, 4)
y_train : (105,), y_test : (45,)

In [12]:
y_train.value_counts()

class
versicolor    37
virginica     37
setosa        31
Name: count, dtype: int64

In [13]:
# shuffle을 False로 바꿔서 사용하게 되면?
X_train2, X_test2, y_train2, y_text2 = train_test_split(
    x, y, test_size=0.3, shuffle=False
)

In [14]:
X_train2.shape

(105, 4)

In [15]:
y_train2.value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [16]:
iris.loc[: 104, 'class'].value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [17]:
# 데이터 비율에 맞춰서 분할
X_train3, X_test3, y_train3, y_test3 = train_test_split(
    x, y, test_size=0.3, random_state=42, stratify=y
)

In [18]:
X_train3.shape

(105, 4)

In [19]:
y_train3

98     versicolor
68     versicolor
19         setosa
143     virginica
99     versicolor
          ...
37         setosa
79     versicolor
33         setosa
94     versicolor
3          setosa
Name: class, Length: 105, dtype: object

In [20]:
y_train3.value_counts()

class
versicolor    35
setosa        35
virginica     35
Name: count, dtype: int64

In [21]:
# 계층화 작업을 하면 shuffle 무조건 True로 사용
# X_train4, X_test4, y_train4, y_test4 = train_test_split(
#     x, y, test_size=0.3, shuffle=False, stratify=y
# )

In [22]:
y_train2

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
100    virginica
101    virginica
102    virginica
103    virginica
104    virginica
Name: class, Length: 105, dtype: object

### 데이터 스케일링
- 대부분 분석 알고리즘은 컬럼 간 데이터의 범위가 크게 차이나는 경우에는 정상적으로 작동 하지 않는다. ( 성능이 떨어진다. )
- 값의 범위가 작은 컬럼에 비해서 범위가 큰 컬럼이 종속 변수를 예측하는데 큰 영향을 준다고 판단 
- 스케일링 작업은 모든 컬럼의 값의 범위를 같게 만들어주는 작업 
- 스케일링 작업 전에 이상치 데이터를 대체하거나 삭제
- 스케일링 작업 순서 
    - train, test로 나눠져있는 경우  train에서 사용한 scaler를 test에서 사용(일반적인 방법)
    1. Scaler 선택
        - 해당 Scaler를 import 
    2. Scaler 객체(class) 생성
    3. train 데이터의 분포(범위)를 저장 ( fit() )
    4. train 데이터를 스케일링 ( transform() )
    5. test 데이터를 스케일링 ( transform() )
    6. 원본 데이터로 변환 ( inverse_transform() )

#### Standard Scaler
- 표준화 방식으로 가장 기본적인 스케일러 
- 평균이 0, 분산이 1인 정규분포로 스케일링 
- 최솟값과 최대값의 크기를 따로 제한하지 않아 이상치에 민감하기 때문에 이상치에 대한 확인 및 정제를 한 뒤 사용
- 일반적으로 회귀분석보다는 분류분석에서 사용

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
# class 생성 
stdscaler = StandardScaler()

In [25]:
# X_train3 데이터의 범위를 등록 
# Scaler에서 fit() -> 범위를 지정 // transform() -> 지정된 범위를 이용하여 스케일링
# fit_transform() -> fit() + transform()
# train data : fit() -> transform() || fit_transform()
# test data : transform()
stdscaler.fit(X_train3)

StandardScaler()

In [26]:
# train 데이터 스케일링 (변환) -> 따로 제공(함수의 리턴 데이터를 이용하여 원본 데이터를 변화시키지 않고 유지)
X_train_sc = stdscaler.transform(X_train3)

In [27]:
# test 데이터 스케일링 
X_test_sc = stdscaler.transform(X_test3)

In [28]:
# 데이터들의 최솟값과 최댓값 평균, 표준편차를 출력하는 함수를 생성
def scaler_print(train, test):
    print(f"""
        Train Data : 
            Min : {round(train.min(), 2)}
            Max : {round(train.max(), 2)}
            Mean : {round(train.mean(), 2)}
            Std : {round(train.std(), 2)}
    """)
    print(f"""
        test Data : 
            Min : {round(test.min(), 2)}
            Max : {round(test.max(), 2)}
            Mean : {round(test.mean(), 2)}
            Std : {round(test.std(), 2)}
    """)

In [30]:
scaler_print(X_train_sc, X_test_sc)

        Train Data :
            Min : -2.32
            Max : 2.96
            Mean : 0.0
            Std : 1.0


        test Data :
            Min : -1.72
            Max : 2.08
            Mean : -0.04
            Std : 0.9

In [31]:
x_t_s = stdscaler.fit_transform(X_train3)
x_te_s = stdscaler.fit_transform(X_test3)

In [32]:
scaler_print(x_t_s, x_te_s)

        Train Data :
            Min : -2.32
            Max : 2.96
            Mean : 0.0
            Std : 1.0


        test Data :
            Min : -2.0
            Max : 2.46
            Mean : -0.0
            Std : 1.0

In [34]:
scaler_print(X_train3.values, X_test3.values)

        Train Data :
            Min : 0.1
            Max : 7.9
            Mean : 3.48
            Std : 1.99


        test Data :
            Min : 0.2
            Max : 7.3
            Mean : 3.43
            Std : 1.93

#### Min-Max Scaler 
- 정규화 방식으로 컬럼의 데이터들을 0과 1 사이의 값으로 스케일링 하는 방식
- 최솟값 0 최대값 1
- 이상치 매우 민감함으로 이상치 대한 확인 및 정제 필수 
- 일반적으로 분류 분석보다는 회귀 분석에서 사용

In [35]:
from sklearn.preprocessing import MinMaxScaler

mnscaler = MinMaxScaler()

X_train_sc = mnscaler.fit_transform(X_train3)
X_test_sc = mnscaler.transform(X_test3)

scaler_print(X_train_sc, X_test_sc)

        Train Data :
            Min : 0.0
            Max : 1.0
            Mean : 0.45
            Std : 0.27


        test Data :
            Min : -0.02
            Max : 0.96
            Mean : 0.44
            Std : 0.25

#### Max Abs Scaler
- 최대절댓값과 0이 각각 1, 0이 되도록 스케일링을 하는 정규화 방식으로 모든 값은 -1부터 1 사이로 표현
- 스케일링 대상의 데이터가 모두 양수라면 MinMaxScaler와 동일
- 이상치 매우 민감하기 때문에 확인 및 정제 필요
- 일반적으로는 분류 분석보다는 회귀 분석에서 사용

In [37]:
from sklearn.preprocessing import MaxAbsScaler
mascaler = MaxAbsScaler()
X_train_sc = mascaler.fit_transform(X_train3)
X_test_sc = mascaler.transform(X_test3)

scaler_print(X_train_sc, X_test_sc)

        Train Data :
            Min : 0.04
            Max : 1.0
            Mean : 0.62
            Std : 0.24


        test Data :
            Min : 0.08
            Max : 0.96
            Mean : 0.61
            Std : 0.23

#### Robust Scaler
- 평균과 분산을 이용한 Standard 대신에 중앙값과 사분위수를 활용하는 방식
- 중앙값을 0으로 설정, IQR을 사용하여 이상치의 영향을 최소화
- quantile_range 매개변수( 기본값 [25, 75] )의 값을 조정하여 더 넓거나 좁은 범위의 값을 이상치로 판단하게 하여 정제할 수 있다.

In [44]:
from sklearn.preprocessing import RobustScaler
ruscaler = RobustScaler()
ruscaler2 = RobustScaler(quantile_range=(20, 80))

In [45]:
ruscaler.fit(X_train3)

RobustScaler()

In [46]:
ruscaler2.fit(X_train3)

RobustScaler(quantile_range=(20, 80))

In [47]:
X_train_sc = ruscaler.transform(X_train3)
X_test_sc = ruscaler.transform(X_test3)

scaler_print(X_train_sc, X_test_sc)

        Train Data :
            Min : -2.0
            Max : 2.8
            Mean : -0.0
            Std : 0.67


        test Data :
            Min : -1.4
            Max : 2.0
            Mean : -0.03
            Std : 0.59

In [48]:
X_train_sc = ruscaler2.transform(X_train3)
X_test_sc = ruscaler2.transform(X_test3)

scaler_print(X_train_sc, X_test_sc)

        Train Data :
            Min : -1.43
            Max : 2.0
            Mean : -0.01
            Std : 0.53


        test Data :
            Min : -1.0
            Max : 1.43
            Mean : -0.03
            Std : 0.47

In [50]:
pd.DataFrame(X_train_sc).head()

        0         1         2         3
0 -0.4375 -0.714286 -0.306122 -0.111111
1  0.2500 -1.142857  0.076531  0.111111
2 -0.4375  1.142857 -0.688776 -0.555556
3  0.6250  0.285714  0.433673  0.555556
4 -0.0625 -0.285714 -0.025510  0.000000

In [52]:
# 스케일링이 된 데이터를 원본으로 복원 
X_origin = ruscaler2.inverse_transform(X_train_sc)

pd.DataFrame(X_origin).head()

     0    1    2    3
0  5.1  2.5  3.0  1.1
1  6.2  2.2  4.5  1.5
2  5.1  3.8  1.5  0.3
3  6.8  3.2  5.9  2.3
4  5.7  2.8  4.1  1.3

In [53]:
X_train3.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3