In [ ]:
import pandas as pd

In [ ]:
# csv 폴더 안에 있는 corona.csv 파일 로드 
# 현재 작업중인 폴더(./)(생략이 가능) -> 상위 폴더로 이동(../) 
# -> csv 하위 폴더로 이동(csv/) -> corona.csv
# 상대경로는 내 파일의 위치에서부터 시작
corona = pd.read_csv("../csv/corona.csv")

In [ ]:
# 데이터의 확인 : head(), tail()
corona.head()

In [ ]:
corona.tail()

In [ ]:
# 데이터프레임에서 컬럼들의 목록 확인 
# DataFrame라는 Class에는 3개 변수 -> values, index, columns
corona.columns

In [ ]:
# Unnamed: 0 컬럼은 인덱스로 사용이 됬었구나 -> 필요가 없다. -> 해당 컬럼의 데이터는 제거
# seq 컬럼의 데이터는 게시글의 번호 -> 제거 
# 특정 데이터를 제거(drop())
# dropna() -> 매개변수 축 설정(axis) -> 인덱스를 제거할것인가? 컬럼을 제거할것인가?
#           -> 매개변수 inplace -> 원본의 데이터를 변화 시킬것인가
#           -> 결측치를 제거한다
# drop() -> axis, inplace 매개변수 존재  
#       -> 첫번째 인자는 어떠한 것을 제거할것인가?
#       -> drop() 함수에서 기본 설정은 인덱스를 제거 
corona.drop(
    ['Unnamed: 0','seq'], axis=1, inplace=True
)
# 우리가 제거할 컬럼의 개수가 2개
# drop(inplace=True)의 함수를 실행하면 -> 첫번째 실행에서 정상 처리가 되더라도 
# -> 같은 블록을 다시 실행하면 에러 발생 ( 해당 데이터가 제거되고 다시 제거하려니 없다. )

In [ ]:
corona.head(1)

In [ ]:
# 컬럼의 이름을 변경 
# case1 : rename() 함수를 이용하여 컬럼의 이름을 변경 
# 특정 컬럼의 이름을 변경할때 사용
corona.rename(
    columns = {
        'createDt' : '등록일시', 
        'deathCnt' : '총사망자', 
        'decideCnt' : '총확진자', 
        'stateDt' : '기준일', 
        'stateTime' : '기준시간', 
        'updateDt' : '수정일시', 
        'accExamCnt' : '누적의심자', 
        'accDefRate' : '누적확진율'
    }
)

In [ ]:
# case2 : Class 내부의 columns 변수에 접근해서 다른 데이터를 대입 
# ( 데이터를 변경하기 전에 확인은 불가능 ) 
# -> 이 방법은 모든 컬럼의 이름을 변경할때 주로 사용
# 주의사항 : 컬럼의 개수가 같은 자료형 데이터를 대입 (길이가 다르면 에러 발생)
corona.columns = ['등록일시', '총사망자', '총확진자', '기준일', 
                  '기준시간', '수정일시', '누적의심자', '누적확진율']

In [ ]:
corona.head(1)

In [ ]:
corona.head(10)

In [ ]:
# 데이터를 확인하는 방법 : info(), isna().sum(), describe()
corona.info()

# 인덱스는 일반적으로 범위형태로 구성
# range(0, 100)
# 시간 데이터(시계열 데이터)
# 일반적으로 인덱스(기준값)는 고유값(primary key)
# 고유값을 사용하는 이유는? -> 전체의 데이터에서 특정 데이터를 찾기 편하기 위함
# 개인 정보의 데이터 -> 이름, 생년월일, 주소 ( 3개의 데이터는 고유값을 가질수가 없다. )
#   -> 고유 값 컬럼을 생성 
#   ( 숫자가 1씩 증가하는 형태(auto increament), 주민등록번호, ID )
#   -> 하나의 행, 열에 접근하기 편하기 위해서

In [ ]:
# 결측치의 개수를 확인 -> 결측치가 맞느냐(isna()) -> 합산 (sum())
# F -> 0 , T -> 1 --> 합산을 하면 True의 개수(결측치의 개수)
corona.isna().sum()

In [ ]:
# 통계 정보 확인 -> 일반적으로 수치형 데이터의 통계 정보
corona.describe()

In [ ]:
# 문자형 데이터의 통계 정보? ( 데이터의 개수, 고유값의 개수, 0번 인덱스의 데이터 , 최빈값)
corona[ ['등록일시', '기준시간'] ].describe()

In [ ]:
# 데이터프레임에서 정렬을 변경 
# list에서 정렬을 변경하는 함수 -> sort() 
# (기본적으로는 오름차순, reverse매개변수를 True 변경하면 내림차순)
# 데이터프레임은 정렬을 변경할수 있는 방법 2개 -> index, values(기준이 될수 있는 값을 여러개)
# 데이터프레임은 sort()함수가 2개 존재 -> sort_index(), sort_values()
# corona 데이터에서 등록일시를 기준으로 정렬을 오름차순 정렬로 변경
# sort_values() : 특정 컬럼의 값들을 기준으로 정렬을 오름차순(기본값) / 내림차순
# 오름차순 / 내림차순 : ascending 매개변수를 False로 변경하면 내림차순 
# inplace 매개변수 : 원본 데이터를 수정할것인가?
corona.sort_values('등록일시', ascending=True, inplace=True)

In [ ]:
corona.head(3)

In [ ]:
# 인덱스가 역순으로 되어있는게 좀 걸립니다.. 
# 인덱스는 재지정(초기화)
# 초기화(reset) + 인덱스(index)
# 인덱스는 초기화 -> 기존의 인덱스는 index라는 컬럼을 생성하여 데이터를 유지 
# 기존의 인덱스를 제거하려면? -> reset_index().drop('index', axis=1) //
# -> reset_index() 함수 안에 drop 매개변수 존재 
# (기본값은 False, True로 변경하면 기존은 인덱스는 제거) 
corona.reset_index(drop=True, inplace=True)

In [ ]:
# 1차 작업이 종료 -> 백업본 하나 생성 
origin_data = corona.copy()

In [ ]:
# 결측치가 존재하는 컬럼이 3개 (수정일시, 누적의심자, 누적확진율)
# 수정일시가 결측치인 데이터를 확인 ( 수정일시가 결측치인 이유는? -> 수정이 되지 않았다? )
# 수정일시가 결측치인(인덱스의 조건식) 데이터 출력 (전체 데이터에서 특정 데이터들만 확인)
# 데이터프레임에서 수정일시 데이터만 추출 -> 결측치와 같은가?
flag_null = corona['수정일시'].isna()

In [ ]:
corona.loc[flag_null, ]

In [ ]:
# 640인덱스를 기준으로 상위 2개부터 하위 2개까지의 데이터를 출력
# loc[] -> 범위 지정하면 종료값 포함
corona.loc[ 638:642,  ]

In [ ]:
# 누적의심자, 누적확진율
# 결측치가 왜 생겼을까? -> 코로나의 감염자가 재감염이 되는 경우가 발생(많은 수가 발생)
# -> 2개의 컬럼의 데이터의 신뢰도가 떨어져서 데이터를 더 이상 입력하지 않았다. 추측
flag_null2 = corona['누적확진율'].isna()

In [ ]:
corona.loc[flag_null2, ]

In [ ]:
flag_null3 = corona['누적의심자'].isna()

corona.loc[flag_null3, ]

In [ ]:
# 2개의 컬럼의 데이터는 특정 날짜 이후로는 데이터를 수집하지 않았다. 
# 데이터의 필요성 없어졌다. -> 컬럼의 데이터를 제거해도 되겠다 drop 사용 
corona.drop(
    ['누적의심자', '누적확진율'], axis=1, inplace=True
)

In [ ]:
# 데이터셋에서 우리가 필요한 데이터가 존재하지 않는다면 -> 데이터를 생성 
# 일일확진자 -> 어제의 총확진자와 오늘의 총확진자의 수의 차이 
# 파생변수를 생성 -> 컬럼이 하나 추가 
# 일일확진자 = 오늘의 총확진자 - 어제의 총확진자
corona.loc[1, '총확진자'] - corona.loc[0, '총확진자']
corona.loc[2, '총확진자'] - corona.loc[1, '총확진자']
corona.loc[3, '총확진자'] - corona.loc[2, '총확진자']

corona.loc[819, '총확진자'] - corona.loc[818, '총확진자']
# .... 819번 실행 -> 첫날짜는 일일확진자를 계산 불가능 (첫날의 데이터는 0으로 지정)

In [ ]:
new_list = []

# 819번 반복을 하는 반복문 
for i in range(819):
    # i는 0부터 818까지 대입
    result = corona.loc[i+1, '총확진자'] - corona.loc[i, '총확진자']
    # 계산 결과를 new_list에 추가 
    new_list.append(result)

new_list

In [ ]:
new_list2 = [0]

for i in range(1, 820, 1):
    result = corona.loc[i, '총확진자'] - corona.loc[i-1, '총확진자']
    new_list2.append(result)

len(new_list2)

In [ ]:
# 819번 반복하면서 일일확진자의 데이터는 819개 -> 첫번째 데이터는 일일확진자를 구할수 없기 때문
# 첫날의 데이터는 0으로 생성
# 만들어진 리스트에 0을 첫번째 데이터로 대입 -> list.insert(0, 0)
# 리스트 +  리스트 -> 연결 [0] + new_list
# 반복 실행하기 전 new_list를 빈 리스트가 아니라 [0] 대입한 뒤 append()
# case1
[0] + new_list

In [ ]:
# case2 : insert()
new_list.insert(0, 0)

In [ ]:
new_list

In [ ]:
new_list2

In [ ]:
# corona 데이터프레임에 new_list로 만들어준 일일확진자를 대입 
# 데이터프레임은 dict와 비슷한 특성을 가지고 있다. 
# 데이터프레임[new_col] = 1차원 데이터(Series, list, tuple) // 단일 데이터
# 1차원 데이터를 대입하는 경우는 데이터프레임의 인덱스와 길이가 같아야 한다. 
# 단일 데이터를 대입하는 경우 -> 모든 값이 단일데이터로 고정 
corona['일일확진자'] = new_list2

In [ ]:
corona.head()

In [ ]:
# 인덱스 이동(shift) 함수 
# shift()는 기본값은 인덱스는 1씩 이동 (아래로 한칸씩 이동)
# 1차원 데이터중 list - list ?? --> 에러 발생
# numpy의 ndarray형태(행렬) -> 행렬 - 행렬 -> 같은 위치의 원소끼리의 차를 구해서 행렬로 결과
# pandas가 설치될때 numpy가 같이 설치 --> pandas에서 numpy를 사용한다. 
# DataFrame과 Series의 values 값들은 행렬로 표시
# series - series --> 행렬의 차로 계산
# 54 - NaN = NaN // 결측치를 0으로 채운다. 
# 54 - 0 = 54
corona['일일사망자'] = (corona['총사망자'] - corona['총사망자'].shift()).fillna(0)
# int - int -> int 
# 총사망자 shift()를 이용하여 계산을 하면 결측치가 우선 발생 (해당 데이터의 타입이 float 변환)

In [ ]:
corona.head()

In [91]:
# 같은 컬럼내에서 데이터들간의 차이를 구하는 함수 
# diff(n) : n만큼 이동한 데이터와의 차이를 구하는 함수
# diff(1)의 결과는 Series - Series.shift(1) 결과와 같다
corona['일일사망자2'] = corona['총사망자'].diff(1)

In [92]:
corona.tail()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,일일확진자,일일사망자,일일사망자2
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,12039,9.0,9.0
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,9834,20.0,20.0
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,5022,21.0,21.0
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,6172,20.0,20.0
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,13358,6.0,6.0

In [96]:
(corona['일일사망자'] == corona['일일사망자2'].fillna(0)).all()
# all() -> 모든 값이 True인 경우 True -> 하나라도 False가 존재하면 False
# sum() -> 합산 
# any() -> 하나라도 True이면 True -> 모든 데이터가 False라면 False

np.True_

In [98]:
corona['일일사망자2'] = corona['일일사망자2'].fillna(0)

In [100]:
# 파생변수 일일확진자, 일일사망자 생성 -> 확인 
# 일일확진자와 일일사망자 데이터들의 범위는? 0~ xxxx -> 음수가 아니여야된다. 
# 음수인 데이터가 존재하는가? (조건식)
# 일일확진자가 음수라면
corona['일일확진자'] < 0

0      False
1      False
2      False
3      False
4      False
       ...
815    False
816    False
817    False
818    False
819    False
Name: 일일확진자, Length: 820, dtype: bool

In [101]:
# 특정 컬럼의 범위를 찾는다? 최솟값 과 최댓값 --> describe()
corona['일일확진자'].describe()

count       820.000000
mean      22171.569512
std       71013.854189
min        -430.000000
25%         125.000000
50%         642.500000
75%        2782.750000
max      621204.000000
Name: 일일확진자, dtype: float64

In [102]:
corona['일일사망자'].describe()

count    820.000000
mean      29.574390
std       68.530863
min       -2.000000
25%        2.000000
50%        5.000000
75%       20.000000
max      469.000000
Name: 일일사망자, dtype: float64

In [104]:
# 음수인 데이터의 개수를 확인 
(corona['일일확진자'] < 0).sum()

np.int64(1)

In [105]:
(corona['일일사망자'] < 0).sum()

np.int64(1)

In [109]:
# 음수가 왜 발생했는가? 이유는 찾아보자 
# 해당 데이터를 확인 -> 일일사망자, 일일확진자 데이터들이 음수인 모든 데이터를 확인 
flag = (corona[ ['일일사망자', '일일확진자'] ] < 0).any(axis=1)
# flag로 되어있는 데이터셋이 2차원 이상의 데이터셋 
corona.loc[flag, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,일일확진자,일일사망자,일일사망자2
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,-430,-2.0,-2.0

In [110]:
# 2021년 5월 30일 데이터(index 446)에서 음수가 발생 
# 2일전부터 2일후까지의 데이터를 확인 
# 인덱스가 444번부터 448번까지 확인 
corona.loc[444:448, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,일일확진자,일일사망자,일일사망자2
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,533,5.0,5.0
445,2021-05-30 00:00:00.0,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,910,8.0,8.0
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,-430,-2.0,-2.0
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,889,6.0,6.0
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,677,2.0,2.0

In [112]:
# index 445 위치의 등록일시가 잘못 입력되었다. 
# 2021-05-30 00:00:00.0이 아니라 2021-05-31 00:00:00.000 변경
# 데이터프레임에서 데이터를 변경하는 방법 -> 함수를 이용해서 변경 , 
#                           특정 영역을 선택한 뒤 대입 연산자를 이용해서 변경
# 인덱스는 445, 컬럼은 등록일시 의 데이터를 추출하여 다른 데이터로 변환 
corona.loc[445, '등록일시'] = '2021-05-31 00:00:00.000'

In [ ]:
corona.loc[444:448, ]

- 데이터 수정
    1. 등록일시를 기준으로 오름차순 정렬
    2. 인덱스는 초기화하고 기존의 인덱스는 제거 
    3. '일일사망자', '일일사망자2', '일일확진자' 컬럼을 제거 
    4. '일일사망자' 컬럼을 생성하여 shift() 함수를 이용하여 계산
    5. '일일확진자' 컬럼을 생성하여 diff() 함수를 이용하여 계산
    6. 새롭게 생성한 파생변수들 데이터에서 음수가 존재하는가 확인

In [115]:
# 오름차순 정렬 변경 
corona.sort_values('등록일시', inplace=True)

In [ ]:
corona.loc[444:448, ]

In [119]:
# 인덱스를 초기화하고 기존의 인덱스는 제거 
corona.reset_index(drop=True, inplace=True)

In [125]:
# 컬럼의 제거하는 방법 -> drop(  ,axis=1)
corona.drop(
    [ '일일사망자', '일일사망자2', '일일확진자' ], 
    axis=1, inplace = True
)

In [ ]:
# 데이터프레임에서 '등록일시'부터 '수정일시'까지 보겠다
corona.loc[ : , '등록일시' : '수정일시' ]

In [ ]:
# 컬럼의 위치를 변경해서 확인 
corona[ ['등록일시', '수정일시', '총확진자', '총사망자'] ]

In [128]:
# '일일사망자' 컬럼은 shift() 함수를 이용하여 파생변수 생성 
corona['일일사망자'] = \
      (corona['총사망자'] - corona['총사망자'].shift(1)).fillna(0)

In [129]:
# '일일확진자' 컬럼은 diff() 함수를 이용하여 파생변수 생성 
corona['일일확진자'] = corona['총확진자'].diff(1).fillna(0)

In [130]:
flag = (corona[['일일확진자', '일일사망자']] < 0).any(axis=1)

corona.loc[flag, ]

Empty DataFrame
Columns: [등록일시, 총사망자, 총확진자, 기준일, 기준시간, 수정일시, 일일사망자, 일일확진자]
Index: []

In [131]:
corona[ ['일일확진자', '일일사망자'] ].describe()

               일일확진자       일일사망자
count     820.000000  820.000000
mean    22171.569512   29.574390
std     71013.844067   68.530435
min         0.000000    0.000000
25%       125.000000    2.000000
50%       634.000000    5.000000
75%      2782.750000   20.000000
max    621204.000000  469.000000