#### 문제 
- selenium의 webdriver을 이용하여 `https://comp.wisereport.co.kr/company/c1010001.aspx` 주소로 접속 
- 해당 페이지의 html 문서를 불러와서 BeautifulSoup 타입으로 파싱 
- div 태그중 class의 값이 'fl_le' 태그들을 모두 찾는다. 
- 태그들 중 table을 정보가 주요 지표, 어닝서프라이즈 태그들을 추출하여 문자로 변경 
- pandas 에 read_html()을 이용하여 데이터프레임으로 변환
- 해당 데이터프레임들을 DB server에 table1, table2라는 이름으로 저장 (to_sql() 사용)

In [1]:
import pandas as pd 
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from sqlalchemy import create_engine

In [2]:
driver = webdriver.Chrome()

In [3]:
driver.get('https://comp.wisereport.co.kr/company/c1010001.aspx')

In [4]:
# driver의 페이지소스를 python으로 로드 
html_data = driver.page_source

In [5]:
soup = bs(html_data, 'html.parser')

In [6]:
# div 태그중 class 가 fl_le인 태그를 모두 찾는다. 
div_list = soup.find_all(
    'div', 
    attrs = {
        'class' : 'fl_le'
    }
)
len(div_list)

5

In [12]:
# 이 영역중에 주요지표 테이블 영역이랑 어닝서프라이즈 테이블 영역만 확인 
div_list[4]

<div class="half fl_le">
<h6 class="spanCT" tabindex="0">PER 차트</h6>
<a class="viewCT" href="javascript:;" title="레이어로 자료보기"><span class="icon-sprite icon-data" id="ct4">자료보기</span></a>
<div class="gHead" id="gHeadCt4">
<div class="pop-info" id="frmCt4" name="frmCt4"></div>
<a class="blind" href="#sct5"><strong>차트 건너뛰기</strong>"데이터를 차트로 제공하고 있습니다. 차트를 건너뛰고 싶은 경우 이 링크를 선택하시기 바랍니다."</a>

In [15]:
# Tag 안에 찾는 단어가 존재 하는가?
# Tag 데이터에서 모든 콘첸츠 데이터를 추출 -> get_text()
# 우리가 원하는 단어가 존재하는가? -> find(), in 연산자 
list(
    map(
        lambda x :  '주요지표' in x.get_text() or '어닝서프라이즈' in x.get_text(), # x에는 Tag 데이터 대입
        div_list
    )
)

[False, True, True, False, False]

In [12]:
str(div_list[1])

'<div class="fl_le" style="width: 45%">\n<table class="gHead03" style="width: 95%" summary="기업 펀더멘털 실적, 컨센서스 정보 리스트입니다.P/E(지배), P/B(지배), EV/EBITDA. EV/Sales, EPS(지배), BPS(지배), EBITDA, EBIT, 수정DPS, 배당수익률에 대해서 보여주는 리스트입니다.">\n<caption class="blind">기업 펀더멘털 실적, 컨센서스</caption>\n<colgroup>\n<col width="28%"/>\n<col width="24%"/>\n<col width="24%"/>\n<col width="24%"/>\n</colgroup>\n<thead>\n<tr>\n<th style="padding: 0">주요지표</th>\n<th style="padding: 0">2025/12(A)</th>\n<th style="padding: 0">2026/12(E)</th>\n<th class="no-line" style="padding: 0">Fwd. 12M(E)</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<th class="left" scope="row">PER</th>\n<td class="num">33.37</td>\n<td class="num line">5.96</td>\n<td class="num line">5.55</td>\n</tr>\n<tr>\n<th class="left" scope="row">PBR</th>\n<td class="num">3.42</td>\n<td class="num line">2.21</td>\n<td class="num line">1.94</td>\n</tr>\n<tr>\n<th class="left" scope="row">PCR</th>\n<td class="num">17.31</td>\n<td class="num line">4.98</td>\n<td class="num line">4.68</td>\n</tr>\n<tr>\n<th class="left" scope="row">EV/EBITDA</th>\n<td class="num">14.36</td>\n<td class="num line">3.21</td>\n<td class="num line">2.80</td>\n</tr>\n<tr>\n<th class="left" scope="row">EPS</th>\n<td class="num">6,564원</td>\n<td class="num line">36,745원</td>\n<td class="num line">39,438원</td>\n</tr>\n<tr>\n<th class="left" scope="row">BPS</th>\n<td class="num">63,997원</td>\n<td class="num line">99,252원</td>\n<td class="num line">113,104원</td>\n</tr>\n<tr>\n<th class="left" scope="row">EBITDA</th>\n<td class="num">905,276.4억원</td>\n<td class="num line">3,534,695.2억원</td>\n<td class="num line">3,768,787.8억원</td>\n</tr>\n<tr>\n<th class="left" scope="row">현금DPS</th>\n<td class="num">1,668원</td>\n<td class="num line">3,292원</td>\n<td class="num line">2,999원</td>\n</tr>\n<tr>\n<th class="left" scope="row">현금배당수익률</th>\n<td class="num">0.76%</td>\n<td class="num line">1.50%</td>\n<td class="num line">1.37%</td>\n</tr>\n<tr>\n<th class="left" scope="row">회계기준</th>\n<td class="num">연결</td>\n<td class="num line">연결</td>\n<td class="num line">연결</td>\n</tr>\n</tbody>\n</table>\n<dl class="annotation mb-16 per95">\n<dd class="section01 cursor">\n<ul>\n<li>* Fwd. 12M : 익월부터 향후 12개월의 컨센서스 </li>\n</ul>\n</dd>\n<dd class="section02">\n<ul>\n<li>* (A)는 실적, (E)는 컨센서스</li>\n<li>* 컨센서스 : 최근 3개월간 증권사에서 발표한 추정치의 평균</li>\n<li>* 지표 계산 시 주가 : 전 영업일 보통주 수정주가</li>\n<li>* 연결 기업의 당기순이익 및 자본총계는 지배주주 기준</li>\n</ul>\n</dd>\n<dd class="section03"><a class="off text-hide" href="javascript:;" title="주석 펼치기/접기">주석 펼치기/접기</a></dd>\n</dl>\n</div>'

In [ ]:
from io import StringIO

In [18]:
# read_html() 함수를 이용해서 데이터프레임화 
# read_html() 함수의 결과 -> list -> [df, df, df]
# 첫번째 인자 :  Tag로 이루어진 문자열
pd.read_html( StringIO(str(div_list[2])) )

[   어닝서프라이즈 * 단위: 억원, % 어닝서프라이즈 * 단위: 억원, %.1 어닝서프라이즈 * 단위: 억원, %.2  \
 0                 재무연월                  재무연월               2025/09
 1                 영업이익                  컨센서스              101922.8
 2                 영업이익                   잠정치              121000.0
 3                 영업이익              Surprise                 18.72
 4                 영업이익         전분기대비보기전년동기대비                 31.76
 5                  NaN                 전분기대비                158.77
 6                  NaN                   NaN                   NaN
 7                당기순이익                  컨센서스               96001.6
 8                당기순이익                   잠정치           ● 120,064.0
 9                당기순이익              Surprise                 25.06
 10               당기순이익         전분기대비보기전년동기대비                 22.75
 11                 NaN                 전분기대비                143.34
 12     잠정치발표(예정)일/회계기준       잠정치발표(예정)일/회계기준        2025/10/14(연결)

    어닝서프라이즈 * 단위: 억원, %.3 어닝서프라이즈 * 단위: 억원, %.4
 0                2025/12               2026/03
 1               185098.0              401923.4
 2               200000.0              572000.0
 3                   8.05                 42.32
 4                 208.04                755.61
 5                  64.39                184.95
 6                    NaN                   NaN
 7               163415.8              314258.0
 8            ● 192,920.0                   NaN
 9                  18.05                   NaN
 10                154.64                   NaN
 11                 60.68                   NaN
 12        2026/01/08(연결)        2026/04/07(연결)  ]

In [19]:
df1 = pd.read_html(StringIO(str(div_list[1])))[0]
df1

        주요지표   2025/12(A)     2026/12(E)    Fwd. 12M(E)
0        PER        33.37           5.96           5.55
1        PBR         3.42           2.21           1.94
2        PCR        17.31           4.98           4.68
3  EV/EBITDA        14.36           3.21           2.80
4        EPS       6,564원        36,745원        39,438원
5        BPS      63,997원        99,252원       113,104원
6     EBITDA  905,276.4억원  3,534,695.2억원  3,768,787.8억원
7      현금DPS       1,668원         3,292원         2,999원
8    현금배당수익률        0.76%          1.50%          1.37%
9       회계기준           연결             연결             연결

In [20]:
df2 = pd.read_html(StringIO(str(div_list[2])))[0]
df2

,"어닝서프라이즈 * 단위: 억원, %","어닝서프라이즈 * 단위: 억원, %.1","어닝서프라이즈 * 단위: 억원, %.2","어닝서프라이즈 * 단위: 억원, %.3","어닝서프라이즈 * 단위: 억원, %.4"
0,재무연월,재무연월,2025/09,2025/12,2026/03
1,영업이익,컨센서스,101922.8,185098.0,401923.4
2,영업이익,잠정치,121000.0,200000.0,572000.0
3,영업이익,Surprise,18.72,8.05,42.32
4,영업이익,전분기대비보기전년동기대비,31.76,208.04,755.61
5,NaN,전분기대비,158.77,64.39,184.95
6,NaN,NaN,NaN,NaN,NaN
7,당기순이익,컨센서스,96001.6,163415.8,314258.0
8,당기순이익,잠정치,"● 120,064.0","● 192,920.0",NaN
9,당기순이익,Surprise,25.06,18.05,NaN
10,당기순이익,전분기대비보기전년동기대비,22.75,154.64,NaN
11,NaN,전분기대비,143.34,60.68,NaN
12,잠정치발표(예정)일/회계기준,잠정치발표(예정)일/회계기준,2025/10/14(연결),2026/01/08(연결),2026/04/07(연결)

In [21]:
df2.drop(index=6, inplace=True)

In [22]:
df2.iloc[:, 0] = df2.iloc[:, 0].ffill()

In [23]:
df2

,"어닝서프라이즈 * 단위: 억원, %","어닝서프라이즈 * 단위: 억원, %.1","어닝서프라이즈 * 단위: 억원, %.2","어닝서프라이즈 * 단위: 억원, %.3","어닝서프라이즈 * 단위: 억원, %.4"
0,재무연월,재무연월,2025/09,2025/12,2026/03
1,영업이익,컨센서스,101922.8,185098.0,401923.4
2,영업이익,잠정치,121000.0,200000.0,572000.0
3,영업이익,Surprise,18.72,8.05,42.32
4,영업이익,전분기대비보기전년동기대비,31.76,208.04,755.61
5,영업이익,전분기대비,158.77,64.39,184.95
7,당기순이익,컨센서스,96001.6,163415.8,314258.0
8,당기순이익,잠정치,"● 120,064.0","● 192,920.0",NaN
9,당기순이익,Surprise,25.06,18.05,NaN
10,당기순이익,전분기대비보기전년동기대비,22.75,154.64,NaN
11,당기순이익,전분기대비,143.34,60.68,NaN
12,잠정치발표(예정)일/회계기준,잠정치발표(예정)일/회계기준,2025/10/14(연결),2026/01/08(연결),2026/04/07(연결)

In [24]:
engine = create_engine(
    "mysql+pymysql://root:1234@localhost:3306/multicam"
)

In [25]:
df1.to_sql(
    name = 'table1', 
    con = engine
)

10

In [26]:
df2.to_sql(
    name = 'table2', 
    con = engine
)

12